// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/approval"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/creativevariant"
)

// Approval is the model entity for the Approval schema.
type Approval struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// VariantID holds the value of the "variant_id" field.
	VariantID string `json:"variant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status approval.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApprovalQuery when eager-loading is set.
	Edges        ApprovalEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApprovalEdges holds the relations/edges for other nodes in the graph.
type ApprovalEdges struct {
	// Variant holds the value of the variant edge.
	Variant *CreativeVariant `json:"variant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VariantOrErr returns the Variant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApprovalEdges) VariantOrErr() (*CreativeVariant, error) {
	if e.Variant != nil {
		return e.Variant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: creativevariant.Label}
	}
	return nil, &NotLoadedError{edge: "variant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Approval) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case approval.FieldID, approval.FieldOrganizationID, approval.FieldVariantID, approval.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Approval fields.
func (_m *Approval) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case approval.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case approval.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.String
			}
		case approval.FieldVariantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field variant_id", values[i])
			} else if value.Valid {
				_m.VariantID = value.String
			}
		case approval.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = approval.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Approval.
// This includes values selected through modifiers, order, etc.
func (_m *Approval) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVariant queries the "variant" edge of the Approval entity.
func (_m *Approval) QueryVariant() *CreativeVariantQuery {
	return NewApprovalClient(_m.config).QueryVariant(_m)
}

// Update returns a builder for updating this Approval.
// Note that you need to call Approval.Unwrap() before calling this method if this Approval
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Approval) Update() *ApprovalUpdateOne {
	return NewApprovalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Approval entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Approval) Unwrap() *Approval {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Approval is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Approval) String() string {
	var builder strings.Builder
	builder.WriteString("Approval(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(_m.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("variant_id=")
	builder.WriteString(_m.VariantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Approvals is a parsable slice of Approval.
type Approvals []*Approval
