// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/asset"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/creativevariant"
)

// AssetCreate is the builder for creating a Asset entity.
type AssetCreate struct {
	config
	mutation *AssetMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *AssetCreate) SetOrganizationID(v string) *AssetCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *AssetCreate) SetObjectKey(v string) *AssetCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetMediaType sets the "media_type" field.
func (_c *AssetCreate) SetMediaType(v string) *AssetCreate {
	_c.mutation.SetMediaType(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AssetCreate) SetID(v string) *AssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddVariantIDs adds the "variants" edge to the CreativeVariant entity by IDs.
func (_c *AssetCreate) AddVariantIDs(ids ...string) *AssetCreate {
	_c.mutation.AddVariantIDs(ids...)
	return _c
}

// AddVariants adds the "variants" edges to the CreativeVariant entity.
func (_c *AssetCreate) AddVariants(v ...*CreativeVariant) *AssetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVariantIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_c *AssetCreate) Mutation() *AssetMutation {
	return _c.mutation
}

// Save creates the Asset in the database.
func (_c *AssetCreate) Save(ctx context.Context) (*Asset, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetCreate) SaveX(ctx context.Context) *Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "Asset.organization_id"`)}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "Asset.object_key"`)}
	}
	if _, ok := _c.mutation.MediaType(); !ok {
		return &ValidationError{Name: "media_type", err: errors.New(`ent: missing required field "Asset.media_type"`)}
	}
	return nil
}

func (_c *AssetCreate) sqlSave(ctx context.Context) (*Asset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Asset.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetCreate) createSpec() (*Asset, *sqlgraph.CreateSpec) {
	var (
		_node = &Asset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(asset.Table, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(asset.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(asset.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.MediaType(); ok {
		_spec.SetField(asset.FieldMediaType, field.TypeString, value)
		_node.MediaType = value
	}
	if nodes := _c.mutation.VariantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.VariantsTable,
			Columns: []string{asset.VariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creativevariant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssetCreateBulk is the builder for creating many Asset entities in bulk.
type AssetCreateBulk struct {
	config
	err      error
	builders []*AssetCreate
}

// Save creates the Asset entities in the database.
func (_c *AssetCreateBulk) Save(ctx context.Context) ([]*Asset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Asset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetCreateBulk) SaveX(ctx context.Context) []*Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
