// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditdraindelivery"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
)

// AuditDrainDeliveryUpdate is the builder for updating AuditDrainDelivery entities.
type AuditDrainDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *AuditDrainDeliveryMutation
}

// Where appends a list predicates to the AuditDrainDeliveryUpdate builder.
func (_u *AuditDrainDeliveryUpdate) Where(ps ...predicate.AuditDrainDelivery) *AuditDrainDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AuditDrainDeliveryUpdate) SetStatus(v auditdraindelivery.Status) *AuditDrainDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuditDrainDeliveryUpdate) SetNillableStatus(v *auditdraindelivery.Status) *AuditDrainDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *AuditDrainDeliveryUpdate) SetAttemptCount(v int) *AuditDrainDeliveryUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *AuditDrainDeliveryUpdate) SetNillableAttemptCount(v *int) *AuditDrainDeliveryUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *AuditDrainDeliveryUpdate) AddAttemptCount(v int) *AuditDrainDeliveryUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *AuditDrainDeliveryUpdate) SetNextAttemptAt(v time.Time) *AuditDrainDeliveryUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *AuditDrainDeliveryUpdate) SetNillableNextAttemptAt(v *time.Time) *AuditDrainDeliveryUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuditDrainDeliveryUpdate) SetUpdatedAt(v time.Time) *AuditDrainDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AuditDrainDeliveryMutation object of the builder.
func (_u *AuditDrainDeliveryUpdate) Mutation() *AuditDrainDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditDrainDeliveryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditDrainDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditDrainDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditDrainDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuditDrainDeliveryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := auditdraindelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditDrainDeliveryUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := auditdraindelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuditDrainDelivery.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditDrainDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditdraindelivery.Table, auditdraindelivery.Columns, sqlgraph.NewFieldSpec(auditdraindelivery.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(auditdraindelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(auditdraindelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(auditdraindelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(auditdraindelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(auditdraindelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditdraindelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditDrainDeliveryUpdateOne is the builder for updating a single AuditDrainDelivery entity.
type AuditDrainDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditDrainDeliveryMutation
}

// SetStatus sets the "status" field.
func (_u *AuditDrainDeliveryUpdateOne) SetStatus(v auditdraindelivery.Status) *AuditDrainDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuditDrainDeliveryUpdateOne) SetNillableStatus(v *auditdraindelivery.Status) *AuditDrainDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *AuditDrainDeliveryUpdateOne) SetAttemptCount(v int) *AuditDrainDeliveryUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *AuditDrainDeliveryUpdateOne) SetNillableAttemptCount(v *int) *AuditDrainDeliveryUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *AuditDrainDeliveryUpdateOne) AddAttemptCount(v int) *AuditDrainDeliveryUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *AuditDrainDeliveryUpdateOne) SetNextAttemptAt(v time.Time) *AuditDrainDeliveryUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *AuditDrainDeliveryUpdateOne) SetNillableNextAttemptAt(v *time.Time) *AuditDrainDeliveryUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuditDrainDeliveryUpdateOne) SetUpdatedAt(v time.Time) *AuditDrainDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AuditDrainDeliveryMutation object of the builder.
func (_u *AuditDrainDeliveryUpdateOne) Mutation() *AuditDrainDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditDrainDeliveryUpdate builder.
func (_u *AuditDrainDeliveryUpdateOne) Where(ps ...predicate.AuditDrainDelivery) *AuditDrainDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditDrainDeliveryUpdateOne) Select(field string, fields ...string) *AuditDrainDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditDrainDelivery entity.
func (_u *AuditDrainDeliveryUpdateOne) Save(ctx context.Context) (*AuditDrainDelivery, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditDrainDeliveryUpdateOne) SaveX(ctx context.Context) *AuditDrainDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditDrainDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditDrainDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuditDrainDeliveryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := auditdraindelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditDrainDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := auditdraindelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuditDrainDelivery.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditDrainDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *AuditDrainDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditdraindelivery.Table, auditdraindelivery.Columns, sqlgraph.NewFieldSpec(auditdraindelivery.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditDrainDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditdraindelivery.FieldID)
		for _, f := range fields {
			if !auditdraindelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditdraindelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(auditdraindelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(auditdraindelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(auditdraindelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(auditdraindelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(auditdraindelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AuditDrainDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditdraindelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
