// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditlog"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *AuditLogCreate) SetOrganizationID(v string) *AuditLogCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditLogCreate) SetCreatedAt(v time.Time) *AuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableCreatedAt(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AuditLogCreate) SetRequestID(v string) *AuditLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetActorType sets the "actor_type" field.
func (_c *AuditLogCreate) SetActorType(v auditlog.ActorType) *AuditLogCreate {
	_c.mutation.SetActorType(v)
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *AuditLogCreate) SetActorUserID(v string) *AuditLogCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableActorUserID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetActorUserID(*v)
	}
	return _c
}

// SetActorDisplay sets the "actor_display" field.
func (_c *AuditLogCreate) SetActorDisplay(v string) *AuditLogCreate {
	_c.mutation.SetActorDisplay(v)
	return _c
}

// SetNillableActorDisplay sets the "actor_display" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableActorDisplay(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetActorDisplay(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditLogCreate) SetAction(v string) *AuditLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *AuditLogCreate) SetOutcome(v auditlog.Outcome) *AuditLogCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableOutcome(v *auditlog.Outcome) *AuditLogCreate {
	if v != nil {
		_c.SetOutcome(*v)
	}
	return _c
}

// SetEntityType sets the "entity_type" field.
func (_c *AuditLogCreate) SetEntityType(v string) *AuditLogCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *AuditLogCreate) SetEntityID(v string) *AuditLogCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableEntityID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetEntityID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AuditLogCreate) SetMetadata(v map[string]interface{}) *AuditLogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetSearchText sets the "search_text" field.
func (_c *AuditLogCreate) SetSearchText(v string) *AuditLogCreate {
	_c.mutation.SetSearchText(v)
	return _c
}

// SetNillableSearchText sets the "search_text" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableSearchText(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetSearchText(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditLogCreate) SetID(v string) *AuditLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuditLogMutation object of the builder.
func (_c *AuditLogCreate) Mutation() *AuditLogMutation {
	return _c.mutation
}

// Save creates the AuditLog in the database.
func (_c *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		v := auditlog.DefaultOutcome
		_c.mutation.SetOutcome(v)
	}
	if _, ok := _c.mutation.SearchText(); !ok {
		v := auditlog.DefaultSearchText
		_c.mutation.SetSearchText(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditLogCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "AuditLog.organization_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditLog.created_at"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "AuditLog.request_id"`)}
	}
	if _, ok := _c.mutation.ActorType(); !ok {
		return &ValidationError{Name: "actor_type", err: errors.New(`ent: missing required field "AuditLog.actor_type"`)}
	}
	if v, ok := _c.mutation.ActorType(); ok {
		if err := auditlog.ActorTypeValidator(v); err != nil {
			return &ValidationError{Name: "actor_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditLog.action"`)}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "AuditLog.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := auditlog.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "AuditLog.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "AuditLog.entity_type"`)}
	}
	if _, ok := _c.mutation.SearchText(); !ok {
		return &ValidationError{Name: "search_text", err: errors.New(`ent: missing required field "AuditLog.search_text"`)}
	}
	return nil
}

func (_c *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuditLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(auditlog.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.ActorType(); ok {
		_spec.SetField(auditlog.FieldActorType, field.TypeEnum, value)
		_node.ActorType = value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(auditlog.FieldActorUserID, field.TypeString, value)
		_node.ActorUserID = &value
	}
	if value, ok := _c.mutation.ActorDisplay(); ok {
		_spec.SetField(auditlog.FieldActorDisplay, field.TypeString, value)
		_node.ActorDisplay = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(auditlog.FieldOutcome, field.TypeEnum, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(auditlog.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(auditlog.FieldEntityID, field.TypeString, value)
		_node.EntityID = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(auditlog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.SearchText(); ok {
		_spec.SetField(auditlog.FieldSearchText, field.TypeString, value)
		_node.SearchText = value
	}
	return _node, _spec
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
}

// Save creates the AuditLog entities in the database.
func (_c *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
