// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditoutbox"
)

// AuditOutbox is the model entity for the AuditOutbox schema.
type AuditOutbox struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// AuditLogID holds the value of the "audit_log_id" field.
	AuditLogID string `json:"audit_log_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditOutbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditoutbox.FieldID, auditoutbox.FieldAuditLogID:
			values[i] = new(sql.NullString)
		case auditoutbox.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditOutbox fields.
func (_m *AuditOutbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditoutbox.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case auditoutbox.FieldAuditLogID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audit_log_id", values[i])
			} else if value.Valid {
				_m.AuditLogID = value.String
			}
		case auditoutbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditOutbox.
// This includes values selected through modifiers, order, etc.
func (_m *AuditOutbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuditOutbox.
// Note that you need to call AuditOutbox.Unwrap() before calling this method if this AuditOutbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditOutbox) Update() *AuditOutboxUpdateOne {
	return NewAuditOutboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditOutbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditOutbox) Unwrap() *AuditOutbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditOutbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditOutbox) String() string {
	var builder strings.Builder
	builder.WriteString("AuditOutbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("audit_log_id=")
	builder.WriteString(_m.AuditLogID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuditOutboxes is a parsable slice of AuditOutbox.
type AuditOutboxes []*AuditOutbox
