// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditdraindelivery"
)

// AuditDrainDeliveryCreate is the builder for creating a AuditDrainDelivery entity.
type AuditDrainDeliveryCreate struct {
	config
	mutation *AuditDrainDeliveryMutation
	hooks    []Hook
}

// SetDrainID sets the "drain_id" field.
func (_c *AuditDrainDeliveryCreate) SetDrainID(v string) *AuditDrainDeliveryCreate {
	_c.mutation.SetDrainID(v)
	return _c
}

// SetOutboxID sets the "outbox_id" field.
func (_c *AuditDrainDeliveryCreate) SetOutboxID(v string) *AuditDrainDeliveryCreate {
	_c.mutation.SetOutboxID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AuditDrainDeliveryCreate) SetStatus(v auditdraindelivery.Status) *AuditDrainDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AuditDrainDeliveryCreate) SetNillableStatus(v *auditdraindelivery.Status) *AuditDrainDeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *AuditDrainDeliveryCreate) SetAttemptCount(v int) *AuditDrainDeliveryCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *AuditDrainDeliveryCreate) SetNillableAttemptCount(v *int) *AuditDrainDeliveryCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *AuditDrainDeliveryCreate) SetNextAttemptAt(v time.Time) *AuditDrainDeliveryCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *AuditDrainDeliveryCreate) SetNillableNextAttemptAt(v *time.Time) *AuditDrainDeliveryCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditDrainDeliveryCreate) SetCreatedAt(v time.Time) *AuditDrainDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditDrainDeliveryCreate) SetNillableCreatedAt(v *time.Time) *AuditDrainDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuditDrainDeliveryCreate) SetUpdatedAt(v time.Time) *AuditDrainDeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuditDrainDeliveryCreate) SetNillableUpdatedAt(v *time.Time) *AuditDrainDeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditDrainDeliveryCreate) SetID(v string) *AuditDrainDeliveryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuditDrainDeliveryMutation object of the builder.
func (_c *AuditDrainDeliveryCreate) Mutation() *AuditDrainDeliveryMutation {
	return _c.mutation
}

// Save creates the AuditDrainDelivery in the database.
func (_c *AuditDrainDeliveryCreate) Save(ctx context.Context) (*AuditDrainDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditDrainDeliveryCreate) SaveX(ctx context.Context) *AuditDrainDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditDrainDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditDrainDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditDrainDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := auditdraindelivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := auditdraindelivery.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		v := auditdraindelivery.DefaultNextAttemptAt()
		_c.mutation.SetNextAttemptAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditdraindelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := auditdraindelivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditDrainDeliveryCreate) check() error {
	if _, ok := _c.mutation.DrainID(); !ok {
		return &ValidationError{Name: "drain_id", err: errors.New(`ent: missing required field "AuditDrainDelivery.drain_id"`)}
	}
	if _, ok := _c.mutation.OutboxID(); !ok {
		return &ValidationError{Name: "outbox_id", err: errors.New(`ent: missing required field "AuditDrainDelivery.outbox_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AuditDrainDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := auditdraindelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuditDrainDelivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "AuditDrainDelivery.attempt_count"`)}
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		return &ValidationError{Name: "next_attempt_at", err: errors.New(`ent: missing required field "AuditDrainDelivery.next_attempt_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditDrainDelivery.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuditDrainDelivery.updated_at"`)}
	}
	return nil
}

func (_c *AuditDrainDeliveryCreate) sqlSave(ctx context.Context) (*AuditDrainDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuditDrainDelivery.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditDrainDeliveryCreate) createSpec() (*AuditDrainDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditDrainDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditdraindelivery.Table, sqlgraph.NewFieldSpec(auditdraindelivery.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DrainID(); ok {
		_spec.SetField(auditdraindelivery.FieldDrainID, field.TypeString, value)
		_node.DrainID = value
	}
	if value, ok := _c.mutation.OutboxID(); ok {
		_spec.SetField(auditdraindelivery.FieldOutboxID, field.TypeString, value)
		_node.OutboxID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(auditdraindelivery.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(auditdraindelivery.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(auditdraindelivery.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditdraindelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(auditdraindelivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AuditDrainDeliveryCreateBulk is the builder for creating many AuditDrainDelivery entities in bulk.
type AuditDrainDeliveryCreateBulk struct {
	config
	err      error
	builders []*AuditDrainDeliveryCreate
}

// Save creates the AuditDrainDelivery entities in the database.
func (_c *AuditDrainDeliveryCreateBulk) Save(ctx context.Context) ([]*AuditDrainDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditDrainDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditDrainDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditDrainDeliveryCreateBulk) SaveX(ctx context.Context) []*AuditDrainDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditDrainDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditDrainDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
