// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditoutbox"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
)

// AuditOutboxUpdate is the builder for updating AuditOutbox entities.
type AuditOutboxUpdate struct {
	config
	hooks    []Hook
	mutation *AuditOutboxMutation
}

// Where appends a list predicates to the AuditOutboxUpdate builder.
func (_u *AuditOutboxUpdate) Where(ps ...predicate.AuditOutbox) *AuditOutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the AuditOutboxMutation object of the builder.
func (_u *AuditOutboxUpdate) Mutation() *AuditOutboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditOutboxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditOutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditOutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditOutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditOutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditoutbox.Table, auditoutbox.Columns, sqlgraph.NewFieldSpec(auditoutbox.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditOutboxUpdateOne is the builder for updating a single AuditOutbox entity.
type AuditOutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditOutboxMutation
}

// Mutation returns the AuditOutboxMutation object of the builder.
func (_u *AuditOutboxUpdateOne) Mutation() *AuditOutboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditOutboxUpdate builder.
func (_u *AuditOutboxUpdateOne) Where(ps ...predicate.AuditOutbox) *AuditOutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditOutboxUpdateOne) Select(field string, fields ...string) *AuditOutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditOutbox entity.
func (_u *AuditOutboxUpdateOne) Save(ctx context.Context) (*AuditOutbox, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditOutboxUpdateOne) SaveX(ctx context.Context) *AuditOutbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditOutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditOutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditOutboxUpdateOne) sqlSave(ctx context.Context) (_node *AuditOutbox, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditoutbox.Table, auditoutbox.Columns, sqlgraph.NewFieldSpec(auditoutbox.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditOutbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditoutbox.FieldID)
		for _, f := range fields {
			if !auditoutbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditoutbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &AuditOutbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
