// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditdraindelivery"
)

// AuditDrainDelivery is the model entity for the AuditDrainDelivery schema.
type AuditDrainDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// DrainID holds the value of the "drain_id" field.
	DrainID string `json:"drain_id,omitempty"`
	// OutboxID holds the value of the "outbox_id" field.
	OutboxID string `json:"outbox_id,omitempty"`
	// Status holds the value of the "status" field.
	Status auditdraindelivery.Status `json:"status,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditDrainDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditdraindelivery.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case auditdraindelivery.FieldID, auditdraindelivery.FieldDrainID, auditdraindelivery.FieldOutboxID, auditdraindelivery.FieldStatus:
			values[i] = new(sql.NullString)
		case auditdraindelivery.FieldNextAttemptAt, auditdraindelivery.FieldCreatedAt, auditdraindelivery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditDrainDelivery fields.
func (_m *AuditDrainDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditdraindelivery.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case auditdraindelivery.FieldDrainID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drain_id", values[i])
			} else if value.Valid {
				_m.DrainID = value.String
			}
		case auditdraindelivery.FieldOutboxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outbox_id", values[i])
			} else if value.Valid {
				_m.OutboxID = value.String
			}
		case auditdraindelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = auditdraindelivery.Status(value.String)
			}
		case auditdraindelivery.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case auditdraindelivery.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Time
			}
		case auditdraindelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case auditdraindelivery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditDrainDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *AuditDrainDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuditDrainDelivery.
// Note that you need to call AuditDrainDelivery.Unwrap() before calling this method if this AuditDrainDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditDrainDelivery) Update() *AuditDrainDeliveryUpdateOne {
	return NewAuditDrainDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditDrainDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditDrainDelivery) Unwrap() *AuditDrainDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditDrainDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditDrainDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("AuditDrainDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("drain_id=")
	builder.WriteString(_m.DrainID)
	builder.WriteString(", ")
	builder.WriteString("outbox_id=")
	builder.WriteString(_m.OutboxID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(_m.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuditDrainDeliveries is a parsable slice of AuditDrainDelivery.
type AuditDrainDeliveries []*AuditDrainDelivery
