// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/channelconnection"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/scheduledpost"
)

// ChannelConnectionQuery is the builder for querying ChannelConnection entities.
type ChannelConnectionQuery struct {
	config
	ctx                *QueryContext
	order              []channelconnection.OrderOption
	inters             []Interceptor
	predicates         []predicate.ChannelConnection
	withScheduledPosts *ScheduledPostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChannelConnectionQuery builder.
func (_q *ChannelConnectionQuery) Where(ps ...predicate.ChannelConnection) *ChannelConnectionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChannelConnectionQuery) Limit(limit int) *ChannelConnectionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChannelConnectionQuery) Offset(offset int) *ChannelConnectionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChannelConnectionQuery) Unique(unique bool) *ChannelConnectionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChannelConnectionQuery) Order(o ...channelconnection.OrderOption) *ChannelConnectionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryScheduledPosts chains the current query on the "scheduled_posts" edge.
func (_q *ChannelConnectionQuery) QueryScheduledPosts() *ScheduledPostQuery {
	query := (&ScheduledPostClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channelconnection.Table, channelconnection.FieldID, selector),
			sqlgraph.To(scheduledpost.Table, scheduledpost.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channelconnection.ScheduledPostsTable, channelconnection.ScheduledPostsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChannelConnection entity from the query.
// Returns a *NotFoundError when no ChannelConnection was found.
func (_q *ChannelConnectionQuery) First(ctx context.Context) (*ChannelConnection, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{channelconnection.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChannelConnectionQuery) FirstX(ctx context.Context) *ChannelConnection {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChannelConnection ID from the query.
// Returns a *NotFoundError when no ChannelConnection ID was found.
func (_q *ChannelConnectionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{channelconnection.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChannelConnectionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChannelConnection entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChannelConnection entity is found.
// Returns a *NotFoundError when no ChannelConnection entities are found.
func (_q *ChannelConnectionQuery) Only(ctx context.Context) (*ChannelConnection, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{channelconnection.Label}
	default:
		return nil, &NotSingularError{channelconnection.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChannelConnectionQuery) OnlyX(ctx context.Context) *ChannelConnection {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChannelConnection ID in the query.
// Returns a *NotSingularError when more than one ChannelConnection ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChannelConnectionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{channelconnection.Label}
	default:
		err = &NotSingularError{channelconnection.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChannelConnectionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChannelConnections.
func (_q *ChannelConnectionQuery) All(ctx context.Context) ([]*ChannelConnection, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChannelConnection, *ChannelConnectionQuery]()
	return withInterceptors[[]*ChannelConnection](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChannelConnectionQuery) AllX(ctx context.Context) []*ChannelConnection {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChannelConnection IDs.
func (_q *ChannelConnectionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(channelconnection.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChannelConnectionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChannelConnectionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChannelConnectionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChannelConnectionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChannelConnectionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChannelConnectionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChannelConnectionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChannelConnectionQuery) Clone() *ChannelConnectionQuery {
	if _q == nil {
		return nil
	}
	return &ChannelConnectionQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]channelconnection.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.ChannelConnection{}, _q.predicates...),
		withScheduledPosts: _q.withScheduledPosts.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithScheduledPosts tells the query-builder to eager-load the nodes that are connected to
// the "scheduled_posts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelConnectionQuery) WithScheduledPosts(opts ...func(*ScheduledPostQuery)) *ChannelConnectionQuery {
	query := (&ScheduledPostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScheduledPosts = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrganizationID string `json:"organization_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChannelConnection.Query().
//		GroupBy(channelconnection.FieldOrganizationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChannelConnectionQuery) GroupBy(field string, fields ...string) *ChannelConnectionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChannelConnectionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = channelconnection.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrganizationID string `json:"organization_id,omitempty"`
//	}
//
//	client.ChannelConnection.Query().
//		Select(channelconnection.FieldOrganizationID).
//		Scan(ctx, &v)
func (_q *ChannelConnectionQuery) Select(fields ...string) *ChannelConnectionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChannelConnectionSelect{ChannelConnectionQuery: _q}
	sbuild.label = channelconnection.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChannelConnectionSelect configured with the given aggregations.
func (_q *ChannelConnectionQuery) Aggregate(fns ...AggregateFunc) *ChannelConnectionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChannelConnectionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !channelconnection.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChannelConnectionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChannelConnection, error) {
	var (
		nodes       = []*ChannelConnection{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withScheduledPosts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChannelConnection).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChannelConnection{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withScheduledPosts; query != nil {
		if err := _q.loadScheduledPosts(ctx, query, nodes,
			func(n *ChannelConnection) { n.Edges.ScheduledPosts = []*ScheduledPost{} },
			func(n *ChannelConnection, e *ScheduledPost) {
				n.Edges.ScheduledPosts = append(n.Edges.ScheduledPosts, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChannelConnectionQuery) loadScheduledPosts(ctx context.Context, query *ScheduledPostQuery, nodes []*ChannelConnection, init func(*ChannelConnection), assign func(*ChannelConnection, *ScheduledPost)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*ChannelConnection)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(scheduledpost.FieldChannelConnectionID)
	}
	query.Where(predicate.ScheduledPost(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channelconnection.ScheduledPostsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChannelConnectionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_connection_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChannelConnectionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChannelConnectionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(channelconnection.Table, channelconnection.Columns, sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelconnection.FieldID)
		for i := range fields {
			if fields[i] != channelconnection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChannelConnectionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(channelconnection.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = channelconnection.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChannelConnectionGroupBy is the group-by builder for ChannelConnection entities.
type ChannelConnectionGroupBy struct {
	selector
	build *ChannelConnectionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChannelConnectionGroupBy) Aggregate(fns ...AggregateFunc) *ChannelConnectionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChannelConnectionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelConnectionQuery, *ChannelConnectionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChannelConnectionGroupBy) sqlScan(ctx context.Context, root *ChannelConnectionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChannelConnectionSelect is the builder for selecting fields of ChannelConnection entities.
type ChannelConnectionSelect struct {
	*ChannelConnectionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChannelConnectionSelect) Aggregate(fns ...AggregateFunc) *ChannelConnectionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChannelConnectionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelConnectionQuery, *ChannelConnectionSelect](ctx, _s.ChannelConnectionQuery, _s, _s.inters, v)
}

func (_s *ChannelConnectionSelect) sqlScan(ctx context.Context, root *ChannelConnectionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
