// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/channelconnection"
)

// ChannelConnection is the model entity for the ChannelConnection schema.
type ChannelConnection struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ExternalAccountID holds the value of the "external_account_id" field.
	ExternalAccountID string `json:"external_account_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// ProviderSettings holds the value of the "provider_settings" field.
	ProviderSettings map[string]interface{} `json:"provider_settings,omitempty"`
	// SecretReference holds the value of the "secret_reference" field.
	SecretReference string `json:"secret_reference,omitempty"`
	// Status holds the value of the "status" field.
	Status channelconnection.Status `json:"status,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID string `json:"created_by_user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelConnectionQuery when eager-loading is set.
	Edges        ChannelConnectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelConnectionEdges holds the relations/edges for other nodes in the graph.
type ChannelConnectionEdges struct {
	// ScheduledPosts holds the value of the scheduled_posts edge.
	ScheduledPosts []*ScheduledPost `json:"scheduled_posts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ScheduledPostsOrErr returns the ScheduledPosts value or an error if the edge
// was not loaded in eager-loading.
func (e ChannelConnectionEdges) ScheduledPostsOrErr() ([]*ScheduledPost, error) {
	if e.loadedTypes[0] {
		return e.ScheduledPosts, nil
	}
	return nil, &NotLoadedError{edge: "scheduled_posts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelConnection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelconnection.FieldProviderSettings:
			values[i] = new([]byte)
		case channelconnection.FieldID, channelconnection.FieldOrganizationID, channelconnection.FieldProvider, channelconnection.FieldExternalAccountID, channelconnection.FieldPlatform, channelconnection.FieldSecretReference, channelconnection.FieldStatus, channelconnection.FieldCreatedByUserID:
			values[i] = new(sql.NullString)
		case channelconnection.FieldCreatedAt, channelconnection.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelConnection fields.
func (_m *ChannelConnection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelconnection.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case channelconnection.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.String
			}
		case channelconnection.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case channelconnection.FieldExternalAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_account_id", values[i])
			} else if value.Valid {
				_m.ExternalAccountID = value.String
			}
		case channelconnection.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case channelconnection.FieldProviderSettings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field provider_settings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProviderSettings); err != nil {
					return fmt.Errorf("unmarshal field provider_settings: %w", err)
				}
			}
		case channelconnection.FieldSecretReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_reference", values[i])
			} else if value.Valid {
				_m.SecretReference = value.String
			}
		case channelconnection.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = channelconnection.Status(value.String)
			}
		case channelconnection.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = value.String
			}
		case channelconnection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelconnection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelConnection.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelConnection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryScheduledPosts queries the "scheduled_posts" edge of the ChannelConnection entity.
func (_m *ChannelConnection) QueryScheduledPosts() *ScheduledPostQuery {
	return NewChannelConnectionClient(_m.config).QueryScheduledPosts(_m)
}

// Update returns a builder for updating this ChannelConnection.
// Note that you need to call ChannelConnection.Unwrap() before calling this method if this ChannelConnection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelConnection) Update() *ChannelConnectionUpdateOne {
	return NewChannelConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelConnection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelConnection) Unwrap() *ChannelConnection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelConnection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelConnection) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelConnection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(_m.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("external_account_id=")
	builder.WriteString(_m.ExternalAccountID)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("provider_settings=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderSettings))
	builder.WriteString(", ")
	builder.WriteString("secret_reference=")
	builder.WriteString(_m.SecretReference)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_by_user_id=")
	builder.WriteString(_m.CreatedByUserID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelConnections is a parsable slice of ChannelConnection.
type ChannelConnections []*ChannelConnection
