// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/channelconnection"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/scheduledpost"
)

// ChannelConnectionCreate is the builder for creating a ChannelConnection entity.
type ChannelConnectionCreate struct {
	config
	mutation *ChannelConnectionMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *ChannelConnectionCreate) SetOrganizationID(v string) *ChannelConnectionCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ChannelConnectionCreate) SetProvider(v string) *ChannelConnectionCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ChannelConnectionCreate) SetNillableProvider(v *string) *ChannelConnectionCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetExternalAccountID sets the "external_account_id" field.
func (_c *ChannelConnectionCreate) SetExternalAccountID(v string) *ChannelConnectionCreate {
	_c.mutation.SetExternalAccountID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *ChannelConnectionCreate) SetPlatform(v string) *ChannelConnectionCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *ChannelConnectionCreate) SetNillablePlatform(v *string) *ChannelConnectionCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetProviderSettings sets the "provider_settings" field.
func (_c *ChannelConnectionCreate) SetProviderSettings(v map[string]interface{}) *ChannelConnectionCreate {
	_c.mutation.SetProviderSettings(v)
	return _c
}

// SetSecretReference sets the "secret_reference" field.
func (_c *ChannelConnectionCreate) SetSecretReference(v string) *ChannelConnectionCreate {
	_c.mutation.SetSecretReference(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelConnectionCreate) SetStatus(v channelconnection.Status) *ChannelConnectionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChannelConnectionCreate) SetNillableStatus(v *channelconnection.Status) *ChannelConnectionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *ChannelConnectionCreate) SetCreatedByUserID(v string) *ChannelConnectionCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelConnectionCreate) SetCreatedAt(v time.Time) *ChannelConnectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelConnectionCreate) SetNillableCreatedAt(v *time.Time) *ChannelConnectionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelConnectionCreate) SetUpdatedAt(v time.Time) *ChannelConnectionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelConnectionCreate) SetNillableUpdatedAt(v *time.Time) *ChannelConnectionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelConnectionCreate) SetID(v string) *ChannelConnectionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddScheduledPostIDs adds the "scheduled_posts" edge to the ScheduledPost entity by IDs.
func (_c *ChannelConnectionCreate) AddScheduledPostIDs(ids ...string) *ChannelConnectionCreate {
	_c.mutation.AddScheduledPostIDs(ids...)
	return _c
}

// AddScheduledPosts adds the "scheduled_posts" edges to the ScheduledPost entity.
func (_c *ChannelConnectionCreate) AddScheduledPosts(v ...*ScheduledPost) *ChannelConnectionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScheduledPostIDs(ids...)
}

// Mutation returns the ChannelConnectionMutation object of the builder.
func (_c *ChannelConnectionCreate) Mutation() *ChannelConnectionMutation {
	return _c.mutation
}

// Save creates the ChannelConnection in the database.
func (_c *ChannelConnectionCreate) Save(ctx context.Context) (*ChannelConnection, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelConnectionCreate) SaveX(ctx context.Context) *ChannelConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelConnectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelConnectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelConnectionCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := channelconnection.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := channelconnection.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.ProviderSettings(); !ok {
		v := channelconnection.DefaultProviderSettings
		_c.mutation.SetProviderSettings(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := channelconnection.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelconnection.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := channelconnection.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelConnectionCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "ChannelConnection.organization_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ChannelConnection.provider"`)}
	}
	if _, ok := _c.mutation.ExternalAccountID(); !ok {
		return &ValidationError{Name: "external_account_id", err: errors.New(`ent: missing required field "ChannelConnection.external_account_id"`)}
	}
	if v, ok := _c.mutation.ExternalAccountID(); ok {
		if err := channelconnection.ExternalAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "external_account_id", err: fmt.Errorf(`ent: validator failed for field "ChannelConnection.external_account_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ChannelConnection.platform"`)}
	}
	if _, ok := _c.mutation.ProviderSettings(); !ok {
		return &ValidationError{Name: "provider_settings", err: errors.New(`ent: missing required field "ChannelConnection.provider_settings"`)}
	}
	if _, ok := _c.mutation.SecretReference(); !ok {
		return &ValidationError{Name: "secret_reference", err: errors.New(`ent: missing required field "ChannelConnection.secret_reference"`)}
	}
	if v, ok := _c.mutation.SecretReference(); ok {
		if err := channelconnection.SecretReferenceValidator(v); err != nil {
			return &ValidationError{Name: "secret_reference", err: fmt.Errorf(`ent: validator failed for field "ChannelConnection.secret_reference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelConnection.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channelconnection.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelConnection.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedByUserID(); !ok {
		return &ValidationError{Name: "created_by_user_id", err: errors.New(`ent: missing required field "ChannelConnection.created_by_user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelConnection.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelConnection.updated_at"`)}
	}
	return nil
}

func (_c *ChannelConnectionCreate) sqlSave(ctx context.Context) (*ChannelConnection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ChannelConnection.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelConnectionCreate) createSpec() (*ChannelConnection, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelConnection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelconnection.Table, sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(channelconnection.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(channelconnection.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ExternalAccountID(); ok {
		_spec.SetField(channelconnection.FieldExternalAccountID, field.TypeString, value)
		_node.ExternalAccountID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(channelconnection.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.ProviderSettings(); ok {
		_spec.SetField(channelconnection.FieldProviderSettings, field.TypeJSON, value)
		_node.ProviderSettings = value
	}
	if value, ok := _c.mutation.SecretReference(); ok {
		_spec.SetField(channelconnection.FieldSecretReference, field.TypeString, value)
		_node.SecretReference = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channelconnection.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedByUserID(); ok {
		_spec.SetField(channelconnection.FieldCreatedByUserID, field.TypeString, value)
		_node.CreatedByUserID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelconnection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelconnection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ScheduledPostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelconnection.ScheduledPostsTable,
			Columns: []string{channelconnection.ScheduledPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduledpost.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelConnectionCreateBulk is the builder for creating many ChannelConnection entities in bulk.
type ChannelConnectionCreateBulk struct {
	config
	err      error
	builders []*ChannelConnectionCreate
}

// Save creates the ChannelConnection entities in the database.
func (_c *ChannelConnectionCreateBulk) Save(ctx context.Context) ([]*ChannelConnection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelConnection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelConnectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelConnectionCreateBulk) SaveX(ctx context.Context) []*ChannelConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelConnectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelConnectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
