// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/approval"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/asset"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditdrain"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditdraindelivery"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditlog"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditoutbox"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/channelconnection"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/creativevariant"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/publicationattempt"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/scheduledpost"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/workspacedeletion"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Approval is the client for interacting with the Approval builders.
	Approval *ApprovalClient
	// Asset is the client for interacting with the Asset builders.
	Asset *AssetClient
	// AuditDrain is the client for interacting with the AuditDrain builders.
	AuditDrain *AuditDrainClient
	// AuditDrainDelivery is the client for interacting with the AuditDrainDelivery builders.
	AuditDrainDelivery *AuditDrainDeliveryClient
	// AuditLog is the client for interacting with the AuditLog builders.
	AuditLog *AuditLogClient
	// AuditOutbox is the client for interacting with the AuditOutbox builders.
	AuditOutbox *AuditOutboxClient
	// ChannelConnection is the client for interacting with the ChannelConnection builders.
	ChannelConnection *ChannelConnectionClient
	// CreativeVariant is the client for interacting with the CreativeVariant builders.
	CreativeVariant *CreativeVariantClient
	// PublicationAttempt is the client for interacting with the PublicationAttempt builders.
	PublicationAttempt *PublicationAttemptClient
	// ScheduledPost is the client for interacting with the ScheduledPost builders.
	ScheduledPost *ScheduledPostClient
	// WorkspaceDeletion is the client for interacting with the WorkspaceDeletion builders.
	WorkspaceDeletion *WorkspaceDeletionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Approval = NewApprovalClient(c.config)
	c.Asset = NewAssetClient(c.config)
	c.AuditDrain = NewAuditDrainClient(c.config)
	c.AuditDrainDelivery = NewAuditDrainDeliveryClient(c.config)
	c.AuditLog = NewAuditLogClient(c.config)
	c.AuditOutbox = NewAuditOutboxClient(c.config)
	c.ChannelConnection = NewChannelConnectionClient(c.config)
	c.CreativeVariant = NewCreativeVariantClient(c.config)
	c.PublicationAttempt = NewPublicationAttemptClient(c.config)
	c.ScheduledPost = NewScheduledPostClient(c.config)
	c.WorkspaceDeletion = NewWorkspaceDeletionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Approval:           NewApprovalClient(cfg),
		Asset:              NewAssetClient(cfg),
		AuditDrain:         NewAuditDrainClient(cfg),
		AuditDrainDelivery: NewAuditDrainDeliveryClient(cfg),
		AuditLog:           NewAuditLogClient(cfg),
		AuditOutbox:        NewAuditOutboxClient(cfg),
		ChannelConnection:  NewChannelConnectionClient(cfg),
		CreativeVariant:    NewCreativeVariantClient(cfg),
		PublicationAttempt: NewPublicationAttemptClient(cfg),
		ScheduledPost:      NewScheduledPostClient(cfg),
		WorkspaceDeletion:  NewWorkspaceDeletionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Approval:           NewApprovalClient(cfg),
		Asset:              NewAssetClient(cfg),
		AuditDrain:         NewAuditDrainClient(cfg),
		AuditDrainDelivery: NewAuditDrainDeliveryClient(cfg),
		AuditLog:           NewAuditLogClient(cfg),
		AuditOutbox:        NewAuditOutboxClient(cfg),
		ChannelConnection:  NewChannelConnectionClient(cfg),
		CreativeVariant:    NewCreativeVariantClient(cfg),
		PublicationAttempt: NewPublicationAttemptClient(cfg),
		ScheduledPost:      NewScheduledPostClient(cfg),
		WorkspaceDeletion:  NewWorkspaceDeletionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Approval.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Approval, c.Asset, c.AuditDrain, c.AuditDrainDelivery, c.AuditLog,
		c.AuditOutbox, c.ChannelConnection, c.CreativeVariant, c.PublicationAttempt,
		c.ScheduledPost, c.WorkspaceDeletion,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Approval, c.Asset, c.AuditDrain, c.AuditDrainDelivery, c.AuditLog,
		c.AuditOutbox, c.ChannelConnection, c.CreativeVariant, c.PublicationAttempt,
		c.ScheduledPost, c.WorkspaceDeletion,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ApprovalMutation:
		return c.Approval.mutate(ctx, m)
	case *AssetMutation:
		return c.Asset.mutate(ctx, m)
	case *AuditDrainMutation:
		return c.AuditDrain.mutate(ctx, m)
	case *AuditDrainDeliveryMutation:
		return c.AuditDrainDelivery.mutate(ctx, m)
	case *AuditLogMutation:
		return c.AuditLog.mutate(ctx, m)
	case *AuditOutboxMutation:
		return c.AuditOutbox.mutate(ctx, m)
	case *ChannelConnectionMutation:
		return c.ChannelConnection.mutate(ctx, m)
	case *CreativeVariantMutation:
		return c.CreativeVariant.mutate(ctx, m)
	case *PublicationAttemptMutation:
		return c.PublicationAttempt.mutate(ctx, m)
	case *ScheduledPostMutation:
		return c.ScheduledPost.mutate(ctx, m)
	case *WorkspaceDeletionMutation:
		return c.WorkspaceDeletion.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ApprovalClient is a client for the Approval schema.
type ApprovalClient struct {
	config
}

// NewApprovalClient returns a client for the Approval from the given config.
func NewApprovalClient(c config) *ApprovalClient {
	return &ApprovalClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `approval.Hooks(f(g(h())))`.
func (c *ApprovalClient) Use(hooks ...Hook) {
	c.hooks.Approval = append(c.hooks.Approval, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `approval.Intercept(f(g(h())))`.
func (c *ApprovalClient) Intercept(interceptors ...Interceptor) {
	c.inters.Approval = append(c.inters.Approval, interceptors...)
}

// Create returns a builder for creating a Approval entity.
func (c *ApprovalClient) Create() *ApprovalCreate {
	mutation := newApprovalMutation(c.config, OpCreate)
	return &ApprovalCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Approval entities.
func (c *ApprovalClient) CreateBulk(builders ...*ApprovalCreate) *ApprovalCreateBulk {
	return &ApprovalCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ApprovalClient) MapCreateBulk(slice any, setFunc func(*ApprovalCreate, int)) *ApprovalCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ApprovalCreateBulk{err: fmt.Errorf("calling to ApprovalClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ApprovalCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ApprovalCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Approval.
func (c *ApprovalClient) Update() *ApprovalUpdate {
	mutation := newApprovalMutation(c.config, OpUpdate)
	return &ApprovalUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ApprovalClient) UpdateOne(_m *Approval) *ApprovalUpdateOne {
	mutation := newApprovalMutation(c.config, OpUpdateOne, withApproval(_m))
	return &ApprovalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ApprovalClient) UpdateOneID(id string) *ApprovalUpdateOne {
	mutation := newApprovalMutation(c.config, OpUpdateOne, withApprovalID(id))
	return &ApprovalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Approval.
func (c *ApprovalClient) Delete() *ApprovalDelete {
	mutation := newApprovalMutation(c.config, OpDelete)
	return &ApprovalDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ApprovalClient) DeleteOne(_m *Approval) *ApprovalDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ApprovalClient) DeleteOneID(id string) *ApprovalDeleteOne {
	builder := c.Delete().Where(approval.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ApprovalDeleteOne{builder}
}

// Query returns a query builder for Approval.
func (c *ApprovalClient) Query() *ApprovalQuery {
	return &ApprovalQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeApproval},
		inters: c.Interceptors(),
	}
}

// Get returns a Approval entity by its id.
func (c *ApprovalClient) Get(ctx context.Context, id string) (*Approval, error) {
	return c.Query().Where(approval.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ApprovalClient) GetX(ctx context.Context, id string) *Approval {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryVariant queries the variant edge of a Approval.
func (c *ApprovalClient) QueryVariant(_m *Approval) *CreativeVariantQuery {
	query := (&CreativeVariantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(approval.Table, approval.FieldID, id),
			sqlgraph.To(creativevariant.Table, creativevariant.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, approval.VariantTable, approval.VariantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ApprovalClient) Hooks() []Hook {
	return c.hooks.Approval
}

// Interceptors returns the client interceptors.
func (c *ApprovalClient) Interceptors() []Interceptor {
	return c.inters.Approval
}

func (c *ApprovalClient) mutate(ctx context.Context, m *ApprovalMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ApprovalCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ApprovalUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ApprovalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ApprovalDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Approval mutation op: %q", m.Op())
	}
}

// AssetClient is a client for the Asset schema.
type AssetClient struct {
	config
}

// NewAssetClient returns a client for the Asset from the given config.
func NewAssetClient(c config) *AssetClient {
	return &AssetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `asset.Hooks(f(g(h())))`.
func (c *AssetClient) Use(hooks ...Hook) {
	c.hooks.Asset = append(c.hooks.Asset, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `asset.Intercept(f(g(h())))`.
func (c *AssetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Asset = append(c.inters.Asset, interceptors...)
}

// Create returns a builder for creating a Asset entity.
func (c *AssetClient) Create() *AssetCreate {
	mutation := newAssetMutation(c.config, OpCreate)
	return &AssetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Asset entities.
func (c *AssetClient) CreateBulk(builders ...*AssetCreate) *AssetCreateBulk {
	return &AssetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AssetClient) MapCreateBulk(slice any, setFunc func(*AssetCreate, int)) *AssetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AssetCreateBulk{err: fmt.Errorf("calling to AssetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AssetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AssetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Asset.
func (c *AssetClient) Update() *AssetUpdate {
	mutation := newAssetMutation(c.config, OpUpdate)
	return &AssetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AssetClient) UpdateOne(_m *Asset) *AssetUpdateOne {
	mutation := newAssetMutation(c.config, OpUpdateOne, withAsset(_m))
	return &AssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AssetClient) UpdateOneID(id string) *AssetUpdateOne {
	mutation := newAssetMutation(c.config, OpUpdateOne, withAssetID(id))
	return &AssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Asset.
func (c *AssetClient) Delete() *AssetDelete {
	mutation := newAssetMutation(c.config, OpDelete)
	return &AssetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AssetClient) DeleteOne(_m *Asset) *AssetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AssetClient) DeleteOneID(id string) *AssetDeleteOne {
	builder := c.Delete().Where(asset.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AssetDeleteOne{builder}
}

// Query returns a query builder for Asset.
func (c *AssetClient) Query() *AssetQuery {
	return &AssetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAsset},
		inters: c.Interceptors(),
	}
}

// Get returns a Asset entity by its id.
func (c *AssetClient) Get(ctx context.Context, id string) (*Asset, error) {
	return c.Query().Where(asset.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AssetClient) GetX(ctx context.Context, id string) *Asset {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryVariants queries the variants edge of a Asset.
func (c *AssetClient) QueryVariants(_m *Asset) *CreativeVariantQuery {
	query := (&CreativeVariantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(asset.Table, asset.FieldID, id),
			sqlgraph.To(creativevariant.Table, creativevariant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, asset.VariantsTable, asset.VariantsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AssetClient) Hooks() []Hook {
	return c.hooks.Asset
}

// Interceptors returns the client interceptors.
func (c *AssetClient) Interceptors() []Interceptor {
	return c.inters.Asset
}

func (c *AssetClient) mutate(ctx context.Context, m *AssetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AssetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AssetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AssetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Asset mutation op: %q", m.Op())
	}
}

// AuditDrainClient is a client for the AuditDrain schema.
type AuditDrainClient struct {
	config
}

// NewAuditDrainClient returns a client for the AuditDrain from the given config.
func NewAuditDrainClient(c config) *AuditDrainClient {
	return &AuditDrainClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditdrain.Hooks(f(g(h())))`.
func (c *AuditDrainClient) Use(hooks ...Hook) {
	c.hooks.AuditDrain = append(c.hooks.AuditDrain, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditdrain.Intercept(f(g(h())))`.
func (c *AuditDrainClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditDrain = append(c.inters.AuditDrain, interceptors...)
}

// Create returns a builder for creating a AuditDrain entity.
func (c *AuditDrainClient) Create() *AuditDrainCreate {
	mutation := newAuditDrainMutation(c.config, OpCreate)
	return &AuditDrainCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditDrain entities.
func (c *AuditDrainClient) CreateBulk(builders ...*AuditDrainCreate) *AuditDrainCreateBulk {
	return &AuditDrainCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditDrainClient) MapCreateBulk(slice any, setFunc func(*AuditDrainCreate, int)) *AuditDrainCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditDrainCreateBulk{err: fmt.Errorf("calling to AuditDrainClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditDrainCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditDrainCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditDrain.
func (c *AuditDrainClient) Update() *AuditDrainUpdate {
	mutation := newAuditDrainMutation(c.config, OpUpdate)
	return &AuditDrainUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditDrainClient) UpdateOne(_m *AuditDrain) *AuditDrainUpdateOne {
	mutation := newAuditDrainMutation(c.config, OpUpdateOne, withAuditDrain(_m))
	return &AuditDrainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditDrainClient) UpdateOneID(id string) *AuditDrainUpdateOne {
	mutation := newAuditDrainMutation(c.config, OpUpdateOne, withAuditDrainID(id))
	return &AuditDrainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditDrain.
func (c *AuditDrainClient) Delete() *AuditDrainDelete {
	mutation := newAuditDrainMutation(c.config, OpDelete)
	return &AuditDrainDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditDrainClient) DeleteOne(_m *AuditDrain) *AuditDrainDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditDrainClient) DeleteOneID(id string) *AuditDrainDeleteOne {
	builder := c.Delete().Where(auditdrain.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditDrainDeleteOne{builder}
}

// Query returns a query builder for AuditDrain.
func (c *AuditDrainClient) Query() *AuditDrainQuery {
	return &AuditDrainQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditDrain},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditDrain entity by its id.
func (c *AuditDrainClient) Get(ctx context.Context, id string) (*AuditDrain, error) {
	return c.Query().Where(auditdrain.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditDrainClient) GetX(ctx context.Context, id string) *AuditDrain {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditDrainClient) Hooks() []Hook {
	return c.hooks.AuditDrain
}

// Interceptors returns the client interceptors.
func (c *AuditDrainClient) Interceptors() []Interceptor {
	return c.inters.AuditDrain
}

func (c *AuditDrainClient) mutate(ctx context.Context, m *AuditDrainMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditDrainCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditDrainUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditDrainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditDrainDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditDrain mutation op: %q", m.Op())
	}
}

// AuditDrainDeliveryClient is a client for the AuditDrainDelivery schema.
type AuditDrainDeliveryClient struct {
	config
}

// NewAuditDrainDeliveryClient returns a client for the AuditDrainDelivery from the given config.
func NewAuditDrainDeliveryClient(c config) *AuditDrainDeliveryClient {
	return &AuditDrainDeliveryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditdraindelivery.Hooks(f(g(h())))`.
func (c *AuditDrainDeliveryClient) Use(hooks ...Hook) {
	c.hooks.AuditDrainDelivery = append(c.hooks.AuditDrainDelivery, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditdraindelivery.Intercept(f(g(h())))`.
func (c *AuditDrainDeliveryClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditDrainDelivery = append(c.inters.AuditDrainDelivery, interceptors...)
}

// Create returns a builder for creating a AuditDrainDelivery entity.
func (c *AuditDrainDeliveryClient) Create() *AuditDrainDeliveryCreate {
	mutation := newAuditDrainDeliveryMutation(c.config, OpCreate)
	return &AuditDrainDeliveryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditDrainDelivery entities.
func (c *AuditDrainDeliveryClient) CreateBulk(builders ...*AuditDrainDeliveryCreate) *AuditDrainDeliveryCreateBulk {
	return &AuditDrainDeliveryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditDrainDeliveryClient) MapCreateBulk(slice any, setFunc func(*AuditDrainDeliveryCreate, int)) *AuditDrainDeliveryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditDrainDeliveryCreateBulk{err: fmt.Errorf("calling to AuditDrainDeliveryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditDrainDeliveryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditDrainDeliveryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditDrainDelivery.
func (c *AuditDrainDeliveryClient) Update() *AuditDrainDeliveryUpdate {
	mutation := newAuditDrainDeliveryMutation(c.config, OpUpdate)
	return &AuditDrainDeliveryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditDrainDeliveryClient) UpdateOne(_m *AuditDrainDelivery) *AuditDrainDeliveryUpdateOne {
	mutation := newAuditDrainDeliveryMutation(c.config, OpUpdateOne, withAuditDrainDelivery(_m))
	return &AuditDrainDeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditDrainDeliveryClient) UpdateOneID(id string) *AuditDrainDeliveryUpdateOne {
	mutation := newAuditDrainDeliveryMutation(c.config, OpUpdateOne, withAuditDrainDeliveryID(id))
	return &AuditDrainDeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditDrainDelivery.
func (c *AuditDrainDeliveryClient) Delete() *AuditDrainDeliveryDelete {
	mutation := newAuditDrainDeliveryMutation(c.config, OpDelete)
	return &AuditDrainDeliveryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditDrainDeliveryClient) DeleteOne(_m *AuditDrainDelivery) *AuditDrainDeliveryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditDrainDeliveryClient) DeleteOneID(id string) *AuditDrainDeliveryDeleteOne {
	builder := c.Delete().Where(auditdraindelivery.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditDrainDeliveryDeleteOne{builder}
}

// Query returns a query builder for AuditDrainDelivery.
func (c *AuditDrainDeliveryClient) Query() *AuditDrainDeliveryQuery {
	return &AuditDrainDeliveryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditDrainDelivery},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditDrainDelivery entity by its id.
func (c *AuditDrainDeliveryClient) Get(ctx context.Context, id string) (*AuditDrainDelivery, error) {
	return c.Query().Where(auditdraindelivery.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditDrainDeliveryClient) GetX(ctx context.Context, id string) *AuditDrainDelivery {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditDrainDeliveryClient) Hooks() []Hook {
	return c.hooks.AuditDrainDelivery
}

// Interceptors returns the client interceptors.
func (c *AuditDrainDeliveryClient) Interceptors() []Interceptor {
	return c.inters.AuditDrainDelivery
}

func (c *AuditDrainDeliveryClient) mutate(ctx context.Context, m *AuditDrainDeliveryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditDrainDeliveryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditDrainDeliveryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditDrainDeliveryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditDrainDeliveryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditDrainDelivery mutation op: %q", m.Op())
	}
}

// AuditLogClient is a client for the AuditLog schema.
type AuditLogClient struct {
	config
}

// NewAuditLogClient returns a client for the AuditLog from the given config.
func NewAuditLogClient(c config) *AuditLogClient {
	return &AuditLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditlog.Hooks(f(g(h())))`.
func (c *AuditLogClient) Use(hooks ...Hook) {
	c.hooks.AuditLog = append(c.hooks.AuditLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditlog.Intercept(f(g(h())))`.
func (c *AuditLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditLog = append(c.inters.AuditLog, interceptors...)
}

// Create returns a builder for creating a AuditLog entity.
func (c *AuditLogClient) Create() *AuditLogCreate {
	mutation := newAuditLogMutation(c.config, OpCreate)
	return &AuditLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditLog entities.
func (c *AuditLogClient) CreateBulk(builders ...*AuditLogCreate) *AuditLogCreateBulk {
	return &AuditLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditLogClient) MapCreateBulk(slice any, setFunc func(*AuditLogCreate, int)) *AuditLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditLogCreateBulk{err: fmt.Errorf("calling to AuditLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditLog.
func (c *AuditLogClient) Update() *AuditLogUpdate {
	mutation := newAuditLogMutation(c.config, OpUpdate)
	return &AuditLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditLogClient) UpdateOne(_m *AuditLog) *AuditLogUpdateOne {
	mutation := newAuditLogMutation(c.config, OpUpdateOne, withAuditLog(_m))
	return &AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditLogClient) UpdateOneID(id string) *AuditLogUpdateOne {
	mutation := newAuditLogMutation(c.config, OpUpdateOne, withAuditLogID(id))
	return &AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditLog.
func (c *AuditLogClient) Delete() *AuditLogDelete {
	mutation := newAuditLogMutation(c.config, OpDelete)
	return &AuditLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditLogClient) DeleteOne(_m *AuditLog) *AuditLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditLogClient) DeleteOneID(id string) *AuditLogDeleteOne {
	builder := c.Delete().Where(auditlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditLogDeleteOne{builder}
}

// Query returns a query builder for AuditLog.
func (c *AuditLogClient) Query() *AuditLogQuery {
	return &AuditLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditLog},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditLog entity by its id.
func (c *AuditLogClient) Get(ctx context.Context, id string) (*AuditLog, error) {
	return c.Query().Where(auditlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditLogClient) GetX(ctx context.Context, id string) *AuditLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditLogClient) Hooks() []Hook {
	return c.hooks.AuditLog
}

// Interceptors returns the client interceptors.
func (c *AuditLogClient) Interceptors() []Interceptor {
	return c.inters.AuditLog
}

func (c *AuditLogClient) mutate(ctx context.Context, m *AuditLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditLog mutation op: %q", m.Op())
	}
}

// AuditOutboxClient is a client for the AuditOutbox schema.
type AuditOutboxClient struct {
	config
}

// NewAuditOutboxClient returns a client for the AuditOutbox from the given config.
func NewAuditOutboxClient(c config) *AuditOutboxClient {
	return &AuditOutboxClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditoutbox.Hooks(f(g(h())))`.
func (c *AuditOutboxClient) Use(hooks ...Hook) {
	c.hooks.AuditOutbox = append(c.hooks.AuditOutbox, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditoutbox.Intercept(f(g(h())))`.
func (c *AuditOutboxClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditOutbox = append(c.inters.AuditOutbox, interceptors...)
}

// Create returns a builder for creating a AuditOutbox entity.
func (c *AuditOutboxClient) Create() *AuditOutboxCreate {
	mutation := newAuditOutboxMutation(c.config, OpCreate)
	return &AuditOutboxCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditOutbox entities.
func (c *AuditOutboxClient) CreateBulk(builders ...*AuditOutboxCreate) *AuditOutboxCreateBulk {
	return &AuditOutboxCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditOutboxClient) MapCreateBulk(slice any, setFunc func(*AuditOutboxCreate, int)) *AuditOutboxCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditOutboxCreateBulk{err: fmt.Errorf("calling to AuditOutboxClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditOutboxCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditOutboxCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditOutbox.
func (c *AuditOutboxClient) Update() *AuditOutboxUpdate {
	mutation := newAuditOutboxMutation(c.config, OpUpdate)
	return &AuditOutboxUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditOutboxClient) UpdateOne(_m *AuditOutbox) *AuditOutboxUpdateOne {
	mutation := newAuditOutboxMutation(c.config, OpUpdateOne, withAuditOutbox(_m))
	return &AuditOutboxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditOutboxClient) UpdateOneID(id string) *AuditOutboxUpdateOne {
	mutation := newAuditOutboxMutation(c.config, OpUpdateOne, withAuditOutboxID(id))
	return &AuditOutboxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditOutbox.
func (c *AuditOutboxClient) Delete() *AuditOutboxDelete {
	mutation := newAuditOutboxMutation(c.config, OpDelete)
	return &AuditOutboxDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditOutboxClient) DeleteOne(_m *AuditOutbox) *AuditOutboxDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditOutboxClient) DeleteOneID(id string) *AuditOutboxDeleteOne {
	builder := c.Delete().Where(auditoutbox.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditOutboxDeleteOne{builder}
}

// Query returns a query builder for AuditOutbox.
func (c *AuditOutboxClient) Query() *AuditOutboxQuery {
	return &AuditOutboxQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditOutbox},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditOutbox entity by its id.
func (c *AuditOutboxClient) Get(ctx context.Context, id string) (*AuditOutbox, error) {
	return c.Query().Where(auditoutbox.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditOutboxClient) GetX(ctx context.Context, id string) *AuditOutbox {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditOutboxClient) Hooks() []Hook {
	return c.hooks.AuditOutbox
}

// Interceptors returns the client interceptors.
func (c *AuditOutboxClient) Interceptors() []Interceptor {
	return c.inters.AuditOutbox
}

func (c *AuditOutboxClient) mutate(ctx context.Context, m *AuditOutboxMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditOutboxCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditOutboxUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditOutboxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditOutboxDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditOutbox mutation op: %q", m.Op())
	}
}

// ChannelConnectionClient is a client for the ChannelConnection schema.
type ChannelConnectionClient struct {
	config
}

// NewChannelConnectionClient returns a client for the ChannelConnection from the given config.
func NewChannelConnectionClient(c config) *ChannelConnectionClient {
	return &ChannelConnectionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channelconnection.Hooks(f(g(h())))`.
func (c *ChannelConnectionClient) Use(hooks ...Hook) {
	c.hooks.ChannelConnection = append(c.hooks.ChannelConnection, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channelconnection.Intercept(f(g(h())))`.
func (c *ChannelConnectionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelConnection = append(c.inters.ChannelConnection, interceptors...)
}

// Create returns a builder for creating a ChannelConnection entity.
func (c *ChannelConnectionClient) Create() *ChannelConnectionCreate {
	mutation := newChannelConnectionMutation(c.config, OpCreate)
	return &ChannelConnectionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelConnection entities.
func (c *ChannelConnectionClient) CreateBulk(builders ...*ChannelConnectionCreate) *ChannelConnectionCreateBulk {
	return &ChannelConnectionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelConnectionClient) MapCreateBulk(slice any, setFunc func(*ChannelConnectionCreate, int)) *ChannelConnectionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelConnectionCreateBulk{err: fmt.Errorf("calling to ChannelConnectionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelConnectionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelConnectionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelConnection.
func (c *ChannelConnectionClient) Update() *ChannelConnectionUpdate {
	mutation := newChannelConnectionMutation(c.config, OpUpdate)
	return &ChannelConnectionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelConnectionClient) UpdateOne(_m *ChannelConnection) *ChannelConnectionUpdateOne {
	mutation := newChannelConnectionMutation(c.config, OpUpdateOne, withChannelConnection(_m))
	return &ChannelConnectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelConnectionClient) UpdateOneID(id string) *ChannelConnectionUpdateOne {
	mutation := newChannelConnectionMutation(c.config, OpUpdateOne, withChannelConnectionID(id))
	return &ChannelConnectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelConnection.
func (c *ChannelConnectionClient) Delete() *ChannelConnectionDelete {
	mutation := newChannelConnectionMutation(c.config, OpDelete)
	return &ChannelConnectionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelConnectionClient) DeleteOne(_m *ChannelConnection) *ChannelConnectionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelConnectionClient) DeleteOneID(id string) *ChannelConnectionDeleteOne {
	builder := c.Delete().Where(channelconnection.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelConnectionDeleteOne{builder}
}

// Query returns a query builder for ChannelConnection.
func (c *ChannelConnectionClient) Query() *ChannelConnectionQuery {
	return &ChannelConnectionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelConnection},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelConnection entity by its id.
func (c *ChannelConnectionClient) Get(ctx context.Context, id string) (*ChannelConnection, error) {
	return c.Query().Where(channelconnection.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelConnectionClient) GetX(ctx context.Context, id string) *ChannelConnection {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryScheduledPosts queries the scheduled_posts edge of a ChannelConnection.
func (c *ChannelConnectionClient) QueryScheduledPosts(_m *ChannelConnection) *ScheduledPostQuery {
	query := (&ScheduledPostClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelconnection.Table, channelconnection.FieldID, id),
			sqlgraph.To(scheduledpost.Table, scheduledpost.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channelconnection.ScheduledPostsTable, channelconnection.ScheduledPostsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelConnectionClient) Hooks() []Hook {
	return c.hooks.ChannelConnection
}

// Interceptors returns the client interceptors.
func (c *ChannelConnectionClient) Interceptors() []Interceptor {
	return c.inters.ChannelConnection
}

func (c *ChannelConnectionClient) mutate(ctx context.Context, m *ChannelConnectionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelConnectionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelConnectionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelConnectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelConnectionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelConnection mutation op: %q", m.Op())
	}
}

// CreativeVariantClient is a client for the CreativeVariant schema.
type CreativeVariantClient struct {
	config
}

// NewCreativeVariantClient returns a client for the CreativeVariant from the given config.
func NewCreativeVariantClient(c config) *CreativeVariantClient {
	return &CreativeVariantClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `creativevariant.Hooks(f(g(h())))`.
func (c *CreativeVariantClient) Use(hooks ...Hook) {
	c.hooks.CreativeVariant = append(c.hooks.CreativeVariant, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `creativevariant.Intercept(f(g(h())))`.
func (c *CreativeVariantClient) Intercept(interceptors ...Interceptor) {
	c.inters.CreativeVariant = append(c.inters.CreativeVariant, interceptors...)
}

// Create returns a builder for creating a CreativeVariant entity.
func (c *CreativeVariantClient) Create() *CreativeVariantCreate {
	mutation := newCreativeVariantMutation(c.config, OpCreate)
	return &CreativeVariantCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CreativeVariant entities.
func (c *CreativeVariantClient) CreateBulk(builders ...*CreativeVariantCreate) *CreativeVariantCreateBulk {
	return &CreativeVariantCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CreativeVariantClient) MapCreateBulk(slice any, setFunc func(*CreativeVariantCreate, int)) *CreativeVariantCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CreativeVariantCreateBulk{err: fmt.Errorf("calling to CreativeVariantClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CreativeVariantCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CreativeVariantCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CreativeVariant.
func (c *CreativeVariantClient) Update() *CreativeVariantUpdate {
	mutation := newCreativeVariantMutation(c.config, OpUpdate)
	return &CreativeVariantUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CreativeVariantClient) UpdateOne(_m *CreativeVariant) *CreativeVariantUpdateOne {
	mutation := newCreativeVariantMutation(c.config, OpUpdateOne, withCreativeVariant(_m))
	return &CreativeVariantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CreativeVariantClient) UpdateOneID(id string) *CreativeVariantUpdateOne {
	mutation := newCreativeVariantMutation(c.config, OpUpdateOne, withCreativeVariantID(id))
	return &CreativeVariantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CreativeVariant.
func (c *CreativeVariantClient) Delete() *CreativeVariantDelete {
	mutation := newCreativeVariantMutation(c.config, OpDelete)
	return &CreativeVariantDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CreativeVariantClient) DeleteOne(_m *CreativeVariant) *CreativeVariantDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CreativeVariantClient) DeleteOneID(id string) *CreativeVariantDeleteOne {
	builder := c.Delete().Where(creativevariant.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CreativeVariantDeleteOne{builder}
}

// Query returns a query builder for CreativeVariant.
func (c *CreativeVariantClient) Query() *CreativeVariantQuery {
	return &CreativeVariantQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCreativeVariant},
		inters: c.Interceptors(),
	}
}

// Get returns a CreativeVariant entity by its id.
func (c *CreativeVariantClient) Get(ctx context.Context, id string) (*CreativeVariant, error) {
	return c.Query().Where(creativevariant.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CreativeVariantClient) GetX(ctx context.Context, id string) *CreativeVariant {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySourceAsset queries the source_asset edge of a CreativeVariant.
func (c *CreativeVariantClient) QuerySourceAsset(_m *CreativeVariant) *AssetQuery {
	query := (&AssetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(creativevariant.Table, creativevariant.FieldID, id),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, creativevariant.SourceAssetTable, creativevariant.SourceAssetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryApproval queries the approval edge of a CreativeVariant.
func (c *CreativeVariantClient) QueryApproval(_m *CreativeVariant) *ApprovalQuery {
	query := (&ApprovalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(creativevariant.Table, creativevariant.FieldID, id),
			sqlgraph.To(approval.Table, approval.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, creativevariant.ApprovalTable, creativevariant.ApprovalColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CreativeVariantClient) Hooks() []Hook {
	return c.hooks.CreativeVariant
}

// Interceptors returns the client interceptors.
func (c *CreativeVariantClient) Interceptors() []Interceptor {
	return c.inters.CreativeVariant
}

func (c *CreativeVariantClient) mutate(ctx context.Context, m *CreativeVariantMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CreativeVariantCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CreativeVariantUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CreativeVariantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CreativeVariantDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CreativeVariant mutation op: %q", m.Op())
	}
}

// PublicationAttemptClient is a client for the PublicationAttempt schema.
type PublicationAttemptClient struct {
	config
}

// NewPublicationAttemptClient returns a client for the PublicationAttempt from the given config.
func NewPublicationAttemptClient(c config) *PublicationAttemptClient {
	return &PublicationAttemptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `publicationattempt.Hooks(f(g(h())))`.
func (c *PublicationAttemptClient) Use(hooks ...Hook) {
	c.hooks.PublicationAttempt = append(c.hooks.PublicationAttempt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `publicationattempt.Intercept(f(g(h())))`.
func (c *PublicationAttemptClient) Intercept(interceptors ...Interceptor) {
	c.inters.PublicationAttempt = append(c.inters.PublicationAttempt, interceptors...)
}

// Create returns a builder for creating a PublicationAttempt entity.
func (c *PublicationAttemptClient) Create() *PublicationAttemptCreate {
	mutation := newPublicationAttemptMutation(c.config, OpCreate)
	return &PublicationAttemptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PublicationAttempt entities.
func (c *PublicationAttemptClient) CreateBulk(builders ...*PublicationAttemptCreate) *PublicationAttemptCreateBulk {
	return &PublicationAttemptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PublicationAttemptClient) MapCreateBulk(slice any, setFunc func(*PublicationAttemptCreate, int)) *PublicationAttemptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PublicationAttemptCreateBulk{err: fmt.Errorf("calling to PublicationAttemptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PublicationAttemptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PublicationAttemptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PublicationAttempt.
func (c *PublicationAttemptClient) Update() *PublicationAttemptUpdate {
	mutation := newPublicationAttemptMutation(c.config, OpUpdate)
	return &PublicationAttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PublicationAttemptClient) UpdateOne(_m *PublicationAttempt) *PublicationAttemptUpdateOne {
	mutation := newPublicationAttemptMutation(c.config, OpUpdateOne, withPublicationAttempt(_m))
	return &PublicationAttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PublicationAttemptClient) UpdateOneID(id string) *PublicationAttemptUpdateOne {
	mutation := newPublicationAttemptMutation(c.config, OpUpdateOne, withPublicationAttemptID(id))
	return &PublicationAttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PublicationAttempt.
func (c *PublicationAttemptClient) Delete() *PublicationAttemptDelete {
	mutation := newPublicationAttemptMutation(c.config, OpDelete)
	return &PublicationAttemptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PublicationAttemptClient) DeleteOne(_m *PublicationAttempt) *PublicationAttemptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PublicationAttemptClient) DeleteOneID(id string) *PublicationAttemptDeleteOne {
	builder := c.Delete().Where(publicationattempt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PublicationAttemptDeleteOne{builder}
}

// Query returns a query builder for PublicationAttempt.
func (c *PublicationAttemptClient) Query() *PublicationAttemptQuery {
	return &PublicationAttemptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePublicationAttempt},
		inters: c.Interceptors(),
	}
}

// Get returns a PublicationAttempt entity by its id.
func (c *PublicationAttemptClient) Get(ctx context.Context, id string) (*PublicationAttempt, error) {
	return c.Query().Where(publicationattempt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PublicationAttemptClient) GetX(ctx context.Context, id string) *PublicationAttempt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryScheduledPost queries the scheduled_post edge of a PublicationAttempt.
func (c *PublicationAttemptClient) QueryScheduledPost(_m *PublicationAttempt) *ScheduledPostQuery {
	query := (&ScheduledPostClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(publicationattempt.Table, publicationattempt.FieldID, id),
			sqlgraph.To(scheduledpost.Table, scheduledpost.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, publicationattempt.ScheduledPostTable, publicationattempt.ScheduledPostColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PublicationAttemptClient) Hooks() []Hook {
	return c.hooks.PublicationAttempt
}

// Interceptors returns the client interceptors.
func (c *PublicationAttemptClient) Interceptors() []Interceptor {
	return c.inters.PublicationAttempt
}

func (c *PublicationAttemptClient) mutate(ctx context.Context, m *PublicationAttemptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PublicationAttemptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PublicationAttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PublicationAttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PublicationAttemptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PublicationAttempt mutation op: %q", m.Op())
	}
}

// ScheduledPostClient is a client for the ScheduledPost schema.
type ScheduledPostClient struct {
	config
}

// NewScheduledPostClient returns a client for the ScheduledPost from the given config.
func NewScheduledPostClient(c config) *ScheduledPostClient {
	return &ScheduledPostClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `scheduledpost.Hooks(f(g(h())))`.
func (c *ScheduledPostClient) Use(hooks ...Hook) {
	c.hooks.ScheduledPost = append(c.hooks.ScheduledPost, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `scheduledpost.Intercept(f(g(h())))`.
func (c *ScheduledPostClient) Intercept(interceptors ...Interceptor) {
	c.inters.ScheduledPost = append(c.inters.ScheduledPost, interceptors...)
}

// Create returns a builder for creating a ScheduledPost entity.
func (c *ScheduledPostClient) Create() *ScheduledPostCreate {
	mutation := newScheduledPostMutation(c.config, OpCreate)
	return &ScheduledPostCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ScheduledPost entities.
func (c *ScheduledPostClient) CreateBulk(builders ...*ScheduledPostCreate) *ScheduledPostCreateBulk {
	return &ScheduledPostCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScheduledPostClient) MapCreateBulk(slice any, setFunc func(*ScheduledPostCreate, int)) *ScheduledPostCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScheduledPostCreateBulk{err: fmt.Errorf("calling to ScheduledPostClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScheduledPostCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScheduledPostCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ScheduledPost.
func (c *ScheduledPostClient) Update() *ScheduledPostUpdate {
	mutation := newScheduledPostMutation(c.config, OpUpdate)
	return &ScheduledPostUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScheduledPostClient) UpdateOne(_m *ScheduledPost) *ScheduledPostUpdateOne {
	mutation := newScheduledPostMutation(c.config, OpUpdateOne, withScheduledPost(_m))
	return &ScheduledPostUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScheduledPostClient) UpdateOneID(id string) *ScheduledPostUpdateOne {
	mutation := newScheduledPostMutation(c.config, OpUpdateOne, withScheduledPostID(id))
	return &ScheduledPostUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ScheduledPost.
func (c *ScheduledPostClient) Delete() *ScheduledPostDelete {
	mutation := newScheduledPostMutation(c.config, OpDelete)
	return &ScheduledPostDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScheduledPostClient) DeleteOne(_m *ScheduledPost) *ScheduledPostDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScheduledPostClient) DeleteOneID(id string) *ScheduledPostDeleteOne {
	builder := c.Delete().Where(scheduledpost.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScheduledPostDeleteOne{builder}
}

// Query returns a query builder for ScheduledPost.
func (c *ScheduledPostClient) Query() *ScheduledPostQuery {
	return &ScheduledPostQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeScheduledPost},
		inters: c.Interceptors(),
	}
}

// Get returns a ScheduledPost entity by its id.
func (c *ScheduledPostClient) Get(ctx context.Context, id string) (*ScheduledPost, error) {
	return c.Query().Where(scheduledpost.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScheduledPostClient) GetX(ctx context.Context, id string) *ScheduledPost {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannelConnection queries the channel_connection edge of a ScheduledPost.
func (c *ScheduledPostClient) QueryChannelConnection(_m *ScheduledPost) *ChannelConnectionQuery {
	query := (&ChannelConnectionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(scheduledpost.Table, scheduledpost.FieldID, id),
			sqlgraph.To(channelconnection.Table, channelconnection.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scheduledpost.ChannelConnectionTable, scheduledpost.ChannelConnectionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAttempts queries the attempts edge of a ScheduledPost.
func (c *ScheduledPostClient) QueryAttempts(_m *ScheduledPost) *PublicationAttemptQuery {
	query := (&PublicationAttemptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(scheduledpost.Table, scheduledpost.FieldID, id),
			sqlgraph.To(publicationattempt.Table, publicationattempt.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, scheduledpost.AttemptsTable, scheduledpost.AttemptsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ScheduledPostClient) Hooks() []Hook {
	return c.hooks.ScheduledPost
}

// Interceptors returns the client interceptors.
func (c *ScheduledPostClient) Interceptors() []Interceptor {
	return c.inters.ScheduledPost
}

func (c *ScheduledPostClient) mutate(ctx context.Context, m *ScheduledPostMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScheduledPostCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScheduledPostUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScheduledPostUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScheduledPostDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ScheduledPost mutation op: %q", m.Op())
	}
}

// WorkspaceDeletionClient is a client for the WorkspaceDeletion schema.
type WorkspaceDeletionClient struct {
	config
}

// NewWorkspaceDeletionClient returns a client for the WorkspaceDeletion from the given config.
func NewWorkspaceDeletionClient(c config) *WorkspaceDeletionClient {
	return &WorkspaceDeletionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workspacedeletion.Hooks(f(g(h())))`.
func (c *WorkspaceDeletionClient) Use(hooks ...Hook) {
	c.hooks.WorkspaceDeletion = append(c.hooks.WorkspaceDeletion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workspacedeletion.Intercept(f(g(h())))`.
func (c *WorkspaceDeletionClient) Intercept(interceptors ...Interceptor) {
	c.inters.WorkspaceDeletion = append(c.inters.WorkspaceDeletion, interceptors...)
}

// Create returns a builder for creating a WorkspaceDeletion entity.
func (c *WorkspaceDeletionClient) Create() *WorkspaceDeletionCreate {
	mutation := newWorkspaceDeletionMutation(c.config, OpCreate)
	return &WorkspaceDeletionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WorkspaceDeletion entities.
func (c *WorkspaceDeletionClient) CreateBulk(builders ...*WorkspaceDeletionCreate) *WorkspaceDeletionCreateBulk {
	return &WorkspaceDeletionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkspaceDeletionClient) MapCreateBulk(slice any, setFunc func(*WorkspaceDeletionCreate, int)) *WorkspaceDeletionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkspaceDeletionCreateBulk{err: fmt.Errorf("calling to WorkspaceDeletionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkspaceDeletionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkspaceDeletionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WorkspaceDeletion.
func (c *WorkspaceDeletionClient) Update() *WorkspaceDeletionUpdate {
	mutation := newWorkspaceDeletionMutation(c.config, OpUpdate)
	return &WorkspaceDeletionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkspaceDeletionClient) UpdateOne(_m *WorkspaceDeletion) *WorkspaceDeletionUpdateOne {
	mutation := newWorkspaceDeletionMutation(c.config, OpUpdateOne, withWorkspaceDeletion(_m))
	return &WorkspaceDeletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkspaceDeletionClient) UpdateOneID(id string) *WorkspaceDeletionUpdateOne {
	mutation := newWorkspaceDeletionMutation(c.config, OpUpdateOne, withWorkspaceDeletionID(id))
	return &WorkspaceDeletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WorkspaceDeletion.
func (c *WorkspaceDeletionClient) Delete() *WorkspaceDeletionDelete {
	mutation := newWorkspaceDeletionMutation(c.config, OpDelete)
	return &WorkspaceDeletionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkspaceDeletionClient) DeleteOne(_m *WorkspaceDeletion) *WorkspaceDeletionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkspaceDeletionClient) DeleteOneID(id string) *WorkspaceDeletionDeleteOne {
	builder := c.Delete().Where(workspacedeletion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkspaceDeletionDeleteOne{builder}
}

// Query returns a query builder for WorkspaceDeletion.
func (c *WorkspaceDeletionClient) Query() *WorkspaceDeletionQuery {
	return &WorkspaceDeletionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkspaceDeletion},
		inters: c.Interceptors(),
	}
}

// Get returns a WorkspaceDeletion entity by its id.
func (c *WorkspaceDeletionClient) Get(ctx context.Context, id string) (*WorkspaceDeletion, error) {
	return c.Query().Where(workspacedeletion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkspaceDeletionClient) GetX(ctx context.Context, id string) *WorkspaceDeletion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WorkspaceDeletionClient) Hooks() []Hook {
	return c.hooks.WorkspaceDeletion
}

// Interceptors returns the client interceptors.
func (c *WorkspaceDeletionClient) Interceptors() []Interceptor {
	return c.inters.WorkspaceDeletion
}

func (c *WorkspaceDeletionClient) mutate(ctx context.Context, m *WorkspaceDeletionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkspaceDeletionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkspaceDeletionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkspaceDeletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkspaceDeletionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WorkspaceDeletion mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Approval, Asset, AuditDrain, AuditDrainDelivery, AuditLog, AuditOutbox,
		ChannelConnection, CreativeVariant, PublicationAttempt, ScheduledPost,
		WorkspaceDeletion []ent.Hook
	}
	inters struct {
		Approval, Asset, AuditDrain, AuditDrainDelivery, AuditLog, AuditOutbox,
		ChannelConnection, CreativeVariant, PublicationAttempt, ScheduledPost,
		WorkspaceDeletion []ent.Interceptor
	}
)
