// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/approval"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/asset"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/creativevariant"
)

// CreativeVariantCreate is the builder for creating a CreativeVariant entity.
type CreativeVariantCreate struct {
	config
	mutation *CreativeVariantMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *CreativeVariantCreate) SetOrganizationID(v string) *CreativeVariantCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetSourceAssetID sets the "source_asset_id" field.
func (_c *CreativeVariantCreate) SetSourceAssetID(v string) *CreativeVariantCreate {
	_c.mutation.SetSourceAssetID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CreativeVariantCreate) SetStatus(v creativevariant.Status) *CreativeVariantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CreativeVariantCreate) SetID(v string) *CreativeVariantCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSourceAsset sets the "source_asset" edge to the Asset entity.
func (_c *CreativeVariantCreate) SetSourceAsset(v *Asset) *CreativeVariantCreate {
	return _c.SetSourceAssetID(v.ID)
}

// SetApprovalID sets the "approval" edge to the Approval entity by ID.
func (_c *CreativeVariantCreate) SetApprovalID(id string) *CreativeVariantCreate {
	_c.mutation.SetApprovalID(id)
	return _c
}

// SetNillableApprovalID sets the "approval" edge to the Approval entity by ID if the given value is not nil.
func (_c *CreativeVariantCreate) SetNillableApprovalID(id *string) *CreativeVariantCreate {
	if id != nil {
		_c = _c.SetApprovalID(*id)
	}
	return _c
}

// SetApproval sets the "approval" edge to the Approval entity.
func (_c *CreativeVariantCreate) SetApproval(v *Approval) *CreativeVariantCreate {
	return _c.SetApprovalID(v.ID)
}

// Mutation returns the CreativeVariantMutation object of the builder.
func (_c *CreativeVariantCreate) Mutation() *CreativeVariantMutation {
	return _c.mutation
}

// Save creates the CreativeVariant in the database.
func (_c *CreativeVariantCreate) Save(ctx context.Context) (*CreativeVariant, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreativeVariantCreate) SaveX(ctx context.Context) *CreativeVariant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreativeVariantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreativeVariantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreativeVariantCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "CreativeVariant.organization_id"`)}
	}
	if _, ok := _c.mutation.SourceAssetID(); !ok {
		return &ValidationError{Name: "source_asset_id", err: errors.New(`ent: missing required field "CreativeVariant.source_asset_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CreativeVariant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := creativevariant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreativeVariant.status": %w`, err)}
		}
	}
	if len(_c.mutation.SourceAssetIDs()) == 0 {
		return &ValidationError{Name: "source_asset", err: errors.New(`ent: missing required edge "CreativeVariant.source_asset"`)}
	}
	return nil
}

func (_c *CreativeVariantCreate) sqlSave(ctx context.Context) (*CreativeVariant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CreativeVariant.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreativeVariantCreate) createSpec() (*CreativeVariant, *sqlgraph.CreateSpec) {
	var (
		_node = &CreativeVariant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creativevariant.Table, sqlgraph.NewFieldSpec(creativevariant.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(creativevariant.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(creativevariant.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.SourceAssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   creativevariant.SourceAssetTable,
			Columns: []string{creativevariant.SourceAssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceAssetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApprovalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   creativevariant.ApprovalTable,
			Columns: []string{creativevariant.ApprovalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CreativeVariantCreateBulk is the builder for creating many CreativeVariant entities in bulk.
type CreativeVariantCreateBulk struct {
	config
	err      error
	builders []*CreativeVariantCreate
}

// Save creates the CreativeVariant entities in the database.
func (_c *CreativeVariantCreateBulk) Save(ctx context.Context) ([]*CreativeVariant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreativeVariant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreativeVariantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreativeVariantCreateBulk) SaveX(ctx context.Context) []*CreativeVariant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreativeVariantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreativeVariantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
