// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/publicationattempt"
)

// PublicationAttemptUpdate is the builder for updating PublicationAttempt entities.
type PublicationAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *PublicationAttemptMutation
}

// Where appends a list predicates to the PublicationAttemptUpdate builder.
func (_u *PublicationAttemptUpdate) Where(ps ...predicate.PublicationAttempt) *PublicationAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PublicationAttemptUpdate) SetCompletedAt(v time.Time) *PublicationAttemptUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableCompletedAt(v *time.Time) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PublicationAttemptUpdate) ClearCompletedAt() *PublicationAttemptUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *PublicationAttemptUpdate) SetOutcome(v publicationattempt.Outcome) *PublicationAttemptUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableOutcome(v *publicationattempt.Outcome) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// ClearOutcome clears the value of the "outcome" field.
func (_u *PublicationAttemptUpdate) ClearOutcome() *PublicationAttemptUpdate {
	_u.mutation.ClearOutcome()
	return _u
}

// SetProviderPostID sets the "provider_post_id" field.
func (_u *PublicationAttemptUpdate) SetProviderPostID(v string) *PublicationAttemptUpdate {
	_u.mutation.SetProviderPostID(v)
	return _u
}

// SetNillableProviderPostID sets the "provider_post_id" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableProviderPostID(v *string) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetProviderPostID(*v)
	}
	return _u
}

// ClearProviderPostID clears the value of the "provider_post_id" field.
func (_u *PublicationAttemptUpdate) ClearProviderPostID() *PublicationAttemptUpdate {
	_u.mutation.ClearProviderPostID()
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *PublicationAttemptUpdate) SetFailureCode(v string) *PublicationAttemptUpdate {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableFailureCode(v *string) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (_u *PublicationAttemptUpdate) ClearFailureCode() *PublicationAttemptUpdate {
	_u.mutation.ClearFailureCode()
	return _u
}

// Mutation returns the PublicationAttemptMutation object of the builder.
func (_u *PublicationAttemptUpdate) Mutation() *PublicationAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PublicationAttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PublicationAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PublicationAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PublicationAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PublicationAttemptUpdate) check() error {
	if v, ok := _u.mutation.Outcome(); ok {
		if err := publicationattempt.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.outcome": %w`, err)}
		}
	}
	if _u.mutation.ScheduledPostCleared() && len(_u.mutation.ScheduledPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PublicationAttempt.scheduled_post"`)
	}
	return nil
}

func (_u *PublicationAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(publicationattempt.Table, publicationattempt.Columns, sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(publicationattempt.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(publicationattempt.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(publicationattempt.FieldOutcome, field.TypeEnum, value)
	}
	if _u.mutation.OutcomeCleared() {
		_spec.ClearField(publicationattempt.FieldOutcome, field.TypeEnum)
	}
	if value, ok := _u.mutation.ProviderPostID(); ok {
		_spec.SetField(publicationattempt.FieldProviderPostID, field.TypeString, value)
	}
	if _u.mutation.ProviderPostIDCleared() {
		_spec.ClearField(publicationattempt.FieldProviderPostID, field.TypeString)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(publicationattempt.FieldFailureCode, field.TypeString, value)
	}
	if _u.mutation.FailureCodeCleared() {
		_spec.ClearField(publicationattempt.FieldFailureCode, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publicationattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PublicationAttemptUpdateOne is the builder for updating a single PublicationAttempt entity.
type PublicationAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PublicationAttemptMutation
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PublicationAttemptUpdateOne) SetCompletedAt(v time.Time) *PublicationAttemptUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableCompletedAt(v *time.Time) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PublicationAttemptUpdateOne) ClearCompletedAt() *PublicationAttemptUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *PublicationAttemptUpdateOne) SetOutcome(v publicationattempt.Outcome) *PublicationAttemptUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableOutcome(v *publicationattempt.Outcome) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// ClearOutcome clears the value of the "outcome" field.
func (_u *PublicationAttemptUpdateOne) ClearOutcome() *PublicationAttemptUpdateOne {
	_u.mutation.ClearOutcome()
	return _u
}

// SetProviderPostID sets the "provider_post_id" field.
func (_u *PublicationAttemptUpdateOne) SetProviderPostID(v string) *PublicationAttemptUpdateOne {
	_u.mutation.SetProviderPostID(v)
	return _u
}

// SetNillableProviderPostID sets the "provider_post_id" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableProviderPostID(v *string) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetProviderPostID(*v)
	}
	return _u
}

// ClearProviderPostID clears the value of the "provider_post_id" field.
func (_u *PublicationAttemptUpdateOne) ClearProviderPostID() *PublicationAttemptUpdateOne {
	_u.mutation.ClearProviderPostID()
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *PublicationAttemptUpdateOne) SetFailureCode(v string) *PublicationAttemptUpdateOne {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableFailureCode(v *string) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (_u *PublicationAttemptUpdateOne) ClearFailureCode() *PublicationAttemptUpdateOne {
	_u.mutation.ClearFailureCode()
	return _u
}

// Mutation returns the PublicationAttemptMutation object of the builder.
func (_u *PublicationAttemptUpdateOne) Mutation() *PublicationAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the PublicationAttemptUpdate builder.
func (_u *PublicationAttemptUpdateOne) Where(ps ...predicate.PublicationAttempt) *PublicationAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PublicationAttemptUpdateOne) Select(field string, fields ...string) *PublicationAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PublicationAttempt entity.
func (_u *PublicationAttemptUpdateOne) Save(ctx context.Context) (*PublicationAttempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PublicationAttemptUpdateOne) SaveX(ctx context.Context) *PublicationAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PublicationAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PublicationAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PublicationAttemptUpdateOne) check() error {
	if v, ok := _u.mutation.Outcome(); ok {
		if err := publicationattempt.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.outcome": %w`, err)}
		}
	}
	if _u.mutation.ScheduledPostCleared() && len(_u.mutation.ScheduledPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PublicationAttempt.scheduled_post"`)
	}
	return nil
}

func (_u *PublicationAttemptUpdateOne) sqlSave(ctx context.Context) (_node *PublicationAttempt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(publicationattempt.Table, publicationattempt.Columns, sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PublicationAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publicationattempt.FieldID)
		for _, f := range fields {
			if !publicationattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != publicationattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(publicationattempt.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(publicationattempt.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(publicationattempt.FieldOutcome, field.TypeEnum, value)
	}
	if _u.mutation.OutcomeCleared() {
		_spec.ClearField(publicationattempt.FieldOutcome, field.TypeEnum)
	}
	if value, ok := _u.mutation.ProviderPostID(); ok {
		_spec.SetField(publicationattempt.FieldProviderPostID, field.TypeString, value)
	}
	if _u.mutation.ProviderPostIDCleared() {
		_spec.ClearField(publicationattempt.FieldProviderPostID, field.TypeString)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(publicationattempt.FieldFailureCode, field.TypeString, value)
	}
	if _u.mutation.FailureCodeCleared() {
		_spec.ClearField(publicationattempt.FieldFailureCode, field.TypeString)
	}
	_node = &PublicationAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publicationattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
