// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/publicationattempt"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/scheduledpost"
)

// PublicationAttempt is the model entity for the PublicationAttempt schema.
type PublicationAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// ScheduledPostID holds the value of the "scheduled_post_id" field.
	ScheduledPostID string `json:"scheduled_post_id,omitempty"`
	// AttemptNumber holds the value of the "attempt_number" field.
	AttemptNumber int `json:"attempt_number,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome *publicationattempt.Outcome `json:"outcome,omitempty"`
	// ProviderPostID holds the value of the "provider_post_id" field.
	ProviderPostID *string `json:"provider_post_id,omitempty"`
	// FailureCode holds the value of the "failure_code" field.
	FailureCode *string `json:"failure_code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PublicationAttemptQuery when eager-loading is set.
	Edges        PublicationAttemptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PublicationAttemptEdges holds the relations/edges for other nodes in the graph.
type PublicationAttemptEdges struct {
	// ScheduledPost holds the value of the scheduled_post edge.
	ScheduledPost *ScheduledPost `json:"scheduled_post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ScheduledPostOrErr returns the ScheduledPost value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PublicationAttemptEdges) ScheduledPostOrErr() (*ScheduledPost, error) {
	if e.ScheduledPost != nil {
		return e.ScheduledPost, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: scheduledpost.Label}
	}
	return nil, &NotLoadedError{edge: "scheduled_post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PublicationAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case publicationattempt.FieldAttemptNumber:
			values[i] = new(sql.NullInt64)
		case publicationattempt.FieldID, publicationattempt.FieldOrganizationID, publicationattempt.FieldScheduledPostID, publicationattempt.FieldOutcome, publicationattempt.FieldProviderPostID, publicationattempt.FieldFailureCode:
			values[i] = new(sql.NullString)
		case publicationattempt.FieldStartedAt, publicationattempt.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PublicationAttempt fields.
func (_m *PublicationAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case publicationattempt.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case publicationattempt.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.String
			}
		case publicationattempt.FieldScheduledPostID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_post_id", values[i])
			} else if value.Valid {
				_m.ScheduledPostID = value.String
			}
		case publicationattempt.FieldAttemptNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_number", values[i])
			} else if value.Valid {
				_m.AttemptNumber = int(value.Int64)
			}
		case publicationattempt.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case publicationattempt.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case publicationattempt.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = new(publicationattempt.Outcome)
				*_m.Outcome = publicationattempt.Outcome(value.String)
			}
		case publicationattempt.FieldProviderPostID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_post_id", values[i])
			} else if value.Valid {
				_m.ProviderPostID = new(string)
				*_m.ProviderPostID = value.String
			}
		case publicationattempt.FieldFailureCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_code", values[i])
			} else if value.Valid {
				_m.FailureCode = new(string)
				*_m.FailureCode = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PublicationAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *PublicationAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryScheduledPost queries the "scheduled_post" edge of the PublicationAttempt entity.
func (_m *PublicationAttempt) QueryScheduledPost() *ScheduledPostQuery {
	return NewPublicationAttemptClient(_m.config).QueryScheduledPost(_m)
}

// Update returns a builder for updating this PublicationAttempt.
// Note that you need to call PublicationAttempt.Unwrap() before calling this method if this PublicationAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PublicationAttempt) Update() *PublicationAttemptUpdateOne {
	return NewPublicationAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PublicationAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PublicationAttempt) Unwrap() *PublicationAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PublicationAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PublicationAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("PublicationAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(_m.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("scheduled_post_id=")
	builder.WriteString(_m.ScheduledPostID)
	builder.WriteString(", ")
	builder.WriteString("attempt_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNumber))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Outcome; v != nil {
		builder.WriteString("outcome=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProviderPostID; v != nil {
		builder.WriteString("provider_post_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FailureCode; v != nil {
		builder.WriteString("failure_code=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// PublicationAttempts is a parsable slice of PublicationAttempt.
type PublicationAttempts []*PublicationAttempt
