// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditdrain"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditdraindelivery"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditlog"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/auditoutbox"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/channelconnection"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/publicationattempt"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/scheduledpost"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditdrainFields := schema.AuditDrain{}.Fields()
	_ = auditdrainFields
	// auditdrainDescEnabled is the schema descriptor for enabled field.
	auditdrainDescEnabled := auditdrainFields[2].Descriptor()
	// auditdrain.DefaultEnabled holds the default value on creation for the enabled field.
	auditdrain.DefaultEnabled = auditdrainDescEnabled.Default.(bool)
	auditdraindeliveryFields := schema.AuditDrainDelivery{}.Fields()
	_ = auditdraindeliveryFields
	// auditdraindeliveryDescAttemptCount is the schema descriptor for attempt_count field.
	auditdraindeliveryDescAttemptCount := auditdraindeliveryFields[4].Descriptor()
	// auditdraindelivery.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	auditdraindelivery.DefaultAttemptCount = auditdraindeliveryDescAttemptCount.Default.(int)
	// auditdraindeliveryDescNextAttemptAt is the schema descriptor for next_attempt_at field.
	auditdraindeliveryDescNextAttemptAt := auditdraindeliveryFields[5].Descriptor()
	// auditdraindelivery.DefaultNextAttemptAt holds the default value on creation for the next_attempt_at field.
	auditdraindelivery.DefaultNextAttemptAt = auditdraindeliveryDescNextAttemptAt.Default.(func() time.Time)
	// auditdraindeliveryDescCreatedAt is the schema descriptor for created_at field.
	auditdraindeliveryDescCreatedAt := auditdraindeliveryFields[6].Descriptor()
	// auditdraindelivery.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditdraindelivery.DefaultCreatedAt = auditdraindeliveryDescCreatedAt.Default.(func() time.Time)
	// auditdraindeliveryDescUpdatedAt is the schema descriptor for updated_at field.
	auditdraindeliveryDescUpdatedAt := auditdraindeliveryFields[7].Descriptor()
	// auditdraindelivery.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditdraindelivery.DefaultUpdatedAt = auditdraindeliveryDescUpdatedAt.Default.(func() time.Time)
	// auditdraindelivery.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditdraindelivery.UpdateDefaultUpdatedAt = auditdraindeliveryDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[2].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescSearchText is the schema descriptor for search_text field.
	auditlogDescSearchText := auditlogFields[12].Descriptor()
	// auditlog.DefaultSearchText holds the default value on creation for the search_text field.
	auditlog.DefaultSearchText = auditlogDescSearchText.Default.(string)
	auditoutboxFields := schema.AuditOutbox{}.Fields()
	_ = auditoutboxFields
	// auditoutboxDescCreatedAt is the schema descriptor for created_at field.
	auditoutboxDescCreatedAt := auditoutboxFields[2].Descriptor()
	// auditoutbox.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditoutbox.DefaultCreatedAt = auditoutboxDescCreatedAt.Default.(func() time.Time)
	channelconnectionFields := schema.ChannelConnection{}.Fields()
	_ = channelconnectionFields
	// channelconnectionDescProvider is the schema descriptor for provider field.
	channelconnectionDescProvider := channelconnectionFields[2].Descriptor()
	// channelconnection.DefaultProvider holds the default value on creation for the provider field.
	channelconnection.DefaultProvider = channelconnectionDescProvider.Default.(string)
	// channelconnectionDescExternalAccountID is the schema descriptor for external_account_id field.
	channelconnectionDescExternalAccountID := channelconnectionFields[3].Descriptor()
	// channelconnection.ExternalAccountIDValidator is a validator for the "external_account_id" field. It is called by the builders before save.
	channelconnection.ExternalAccountIDValidator = channelconnectionDescExternalAccountID.Validators[0].(func(string) error)
	// channelconnectionDescPlatform is the schema descriptor for platform field.
	channelconnectionDescPlatform := channelconnectionFields[4].Descriptor()
	// channelconnection.DefaultPlatform holds the default value on creation for the platform field.
	channelconnection.DefaultPlatform = channelconnectionDescPlatform.Default.(string)
	// channelconnectionDescProviderSettings is the schema descriptor for provider_settings field.
	channelconnectionDescProviderSettings := channelconnectionFields[5].Descriptor()
	// channelconnection.DefaultProviderSettings holds the default value on creation for the provider_settings field.
	channelconnection.DefaultProviderSettings = channelconnectionDescProviderSettings.Default.(map[string]interface{})
	// channelconnectionDescSecretReference is the schema descriptor for secret_reference field.
	channelconnectionDescSecretReference := channelconnectionFields[6].Descriptor()
	// channelconnection.SecretReferenceValidator is a validator for the "secret_reference" field. It is called by the builders before save.
	channelconnection.SecretReferenceValidator = channelconnectionDescSecretReference.Validators[0].(func(string) error)
	// channelconnectionDescCreatedAt is the schema descriptor for created_at field.
	channelconnectionDescCreatedAt := channelconnectionFields[9].Descriptor()
	// channelconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	channelconnection.DefaultCreatedAt = channelconnectionDescCreatedAt.Default.(func() time.Time)
	// channelconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	channelconnectionDescUpdatedAt := channelconnectionFields[10].Descriptor()
	// channelconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	channelconnection.DefaultUpdatedAt = channelconnectionDescUpdatedAt.Default.(func() time.Time)
	// channelconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channelconnection.UpdateDefaultUpdatedAt = channelconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	publicationattemptFields := schema.PublicationAttempt{}.Fields()
	_ = publicationattemptFields
	// publicationattemptDescAttemptNumber is the schema descriptor for attempt_number field.
	publicationattemptDescAttemptNumber := publicationattemptFields[3].Descriptor()
	// publicationattempt.AttemptNumberValidator is a validator for the "attempt_number" field. It is called by the builders before save.
	publicationattempt.AttemptNumberValidator = publicationattemptDescAttemptNumber.Validators[0].(func(int) error)
	// publicationattemptDescStartedAt is the schema descriptor for started_at field.
	publicationattemptDescStartedAt := publicationattemptFields[4].Descriptor()
	// publicationattempt.DefaultStartedAt holds the default value on creation for the started_at field.
	publicationattempt.DefaultStartedAt = publicationattemptDescStartedAt.Default.(func() time.Time)
	scheduledpostFields := schema.ScheduledPost{}.Fields()
	_ = scheduledpostFields
	// scheduledpostDescIdempotencyKey is the schema descriptor for idempotency_key field.
	scheduledpostDescIdempotencyKey := scheduledpostFields[7].Descriptor()
	// scheduledpost.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	scheduledpost.IdempotencyKeyValidator = scheduledpostDescIdempotencyKey.Validators[0].(func(string) error)
	// scheduledpostDescCreatedAt is the schema descriptor for created_at field.
	scheduledpostDescCreatedAt := scheduledpostFields[9].Descriptor()
	// scheduledpost.DefaultCreatedAt holds the default value on creation for the created_at field.
	scheduledpost.DefaultCreatedAt = scheduledpostDescCreatedAt.Default.(func() time.Time)
	// scheduledpostDescUpdatedAt is the schema descriptor for updated_at field.
	scheduledpostDescUpdatedAt := scheduledpostFields[10].Descriptor()
	// scheduledpost.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scheduledpost.DefaultUpdatedAt = scheduledpostDescUpdatedAt.Default.(func() time.Time)
	// scheduledpost.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scheduledpost.UpdateDefaultUpdatedAt = scheduledpostDescUpdatedAt.UpdateDefault.(func() time.Time)
}
