// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/publicationattempt"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/scheduledpost"
)

// ScheduledPostUpdate is the builder for updating ScheduledPost entities.
type ScheduledPostUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduledPostMutation
}

// Where appends a list predicates to the ScheduledPostUpdate builder.
func (_u *ScheduledPostUpdate) Where(ps ...predicate.ScheduledPost) *ScheduledPostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScheduledFor sets the "scheduled_for" field.
func (_u *ScheduledPostUpdate) SetScheduledFor(v time.Time) *ScheduledPostUpdate {
	_u.mutation.SetScheduledFor(v)
	return _u
}

// SetNillableScheduledFor sets the "scheduled_for" field if the given value is not nil.
func (_u *ScheduledPostUpdate) SetNillableScheduledFor(v *time.Time) *ScheduledPostUpdate {
	if v != nil {
		_u.SetScheduledFor(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScheduledPostUpdate) SetStatus(v scheduledpost.Status) *ScheduledPostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScheduledPostUpdate) SetNillableStatus(v *scheduledpost.Status) *ScheduledPostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCaption sets the "caption" field.
func (_u *ScheduledPostUpdate) SetCaption(v string) *ScheduledPostUpdate {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *ScheduledPostUpdate) SetNillableCaption(v *string) *ScheduledPostUpdate {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// SetTriggerRunID sets the "trigger_run_id" field.
func (_u *ScheduledPostUpdate) SetTriggerRunID(v string) *ScheduledPostUpdate {
	_u.mutation.SetTriggerRunID(v)
	return _u
}

// SetNillableTriggerRunID sets the "trigger_run_id" field if the given value is not nil.
func (_u *ScheduledPostUpdate) SetNillableTriggerRunID(v *string) *ScheduledPostUpdate {
	if v != nil {
		_u.SetTriggerRunID(*v)
	}
	return _u
}

// ClearTriggerRunID clears the value of the "trigger_run_id" field.
func (_u *ScheduledPostUpdate) ClearTriggerRunID() *ScheduledPostUpdate {
	_u.mutation.ClearTriggerRunID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduledPostUpdate) SetUpdatedAt(v time.Time) *ScheduledPostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAttemptIDs adds the "attempts" edge to the PublicationAttempt entity by IDs.
func (_u *ScheduledPostUpdate) AddAttemptIDs(ids ...string) *ScheduledPostUpdate {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the PublicationAttempt entity.
func (_u *ScheduledPostUpdate) AddAttempts(v ...*PublicationAttempt) *ScheduledPostUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// Mutation returns the ScheduledPostMutation object of the builder.
func (_u *ScheduledPostUpdate) Mutation() *ScheduledPostMutation {
	return _u.mutation
}

// ClearAttempts clears all "attempts" edges to the PublicationAttempt entity.
func (_u *ScheduledPostUpdate) ClearAttempts() *ScheduledPostUpdate {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to PublicationAttempt entities by IDs.
func (_u *ScheduledPostUpdate) RemoveAttemptIDs(ids ...string) *ScheduledPostUpdate {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to PublicationAttempt entities.
func (_u *ScheduledPostUpdate) RemoveAttempts(v ...*PublicationAttempt) *ScheduledPostUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduledPostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduledPostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduledPostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduledPostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduledPostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scheduledpost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduledPostUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := scheduledpost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScheduledPost.status": %w`, err)}
		}
	}
	if _u.mutation.ChannelConnectionCleared() && len(_u.mutation.ChannelConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScheduledPost.channel_connection"`)
	}
	return nil
}

func (_u *ScheduledPostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scheduledpost.Table, scheduledpost.Columns, sqlgraph.NewFieldSpec(scheduledpost.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScheduledFor(); ok {
		_spec.SetField(scheduledpost.FieldScheduledFor, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scheduledpost.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(scheduledpost.FieldCaption, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerRunID(); ok {
		_spec.SetField(scheduledpost.FieldTriggerRunID, field.TypeString, value)
	}
	if _u.mutation.TriggerRunIDCleared() {
		_spec.ClearField(scheduledpost.FieldTriggerRunID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scheduledpost.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduledpost.AttemptsTable,
			Columns: []string{scheduledpost.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduledpost.AttemptsTable,
			Columns: []string{scheduledpost.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduledpost.AttemptsTable,
			Columns: []string{scheduledpost.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scheduledpost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduledPostUpdateOne is the builder for updating a single ScheduledPost entity.
type ScheduledPostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduledPostMutation
}

// SetScheduledFor sets the "scheduled_for" field.
func (_u *ScheduledPostUpdateOne) SetScheduledFor(v time.Time) *ScheduledPostUpdateOne {
	_u.mutation.SetScheduledFor(v)
	return _u
}

// SetNillableScheduledFor sets the "scheduled_for" field if the given value is not nil.
func (_u *ScheduledPostUpdateOne) SetNillableScheduledFor(v *time.Time) *ScheduledPostUpdateOne {
	if v != nil {
		_u.SetScheduledFor(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScheduledPostUpdateOne) SetStatus(v scheduledpost.Status) *ScheduledPostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScheduledPostUpdateOne) SetNillableStatus(v *scheduledpost.Status) *ScheduledPostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCaption sets the "caption" field.
func (_u *ScheduledPostUpdateOne) SetCaption(v string) *ScheduledPostUpdateOne {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *ScheduledPostUpdateOne) SetNillableCaption(v *string) *ScheduledPostUpdateOne {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// SetTriggerRunID sets the "trigger_run_id" field.
func (_u *ScheduledPostUpdateOne) SetTriggerRunID(v string) *ScheduledPostUpdateOne {
	_u.mutation.SetTriggerRunID(v)
	return _u
}

// SetNillableTriggerRunID sets the "trigger_run_id" field if the given value is not nil.
func (_u *ScheduledPostUpdateOne) SetNillableTriggerRunID(v *string) *ScheduledPostUpdateOne {
	if v != nil {
		_u.SetTriggerRunID(*v)
	}
	return _u
}

// ClearTriggerRunID clears the value of the "trigger_run_id" field.
func (_u *ScheduledPostUpdateOne) ClearTriggerRunID() *ScheduledPostUpdateOne {
	_u.mutation.ClearTriggerRunID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduledPostUpdateOne) SetUpdatedAt(v time.Time) *ScheduledPostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAttemptIDs adds the "attempts" edge to the PublicationAttempt entity by IDs.
func (_u *ScheduledPostUpdateOne) AddAttemptIDs(ids ...string) *ScheduledPostUpdateOne {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the PublicationAttempt entity.
func (_u *ScheduledPostUpdateOne) AddAttempts(v ...*PublicationAttempt) *ScheduledPostUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// Mutation returns the ScheduledPostMutation object of the builder.
func (_u *ScheduledPostUpdateOne) Mutation() *ScheduledPostMutation {
	return _u.mutation
}

// ClearAttempts clears all "attempts" edges to the PublicationAttempt entity.
func (_u *ScheduledPostUpdateOne) ClearAttempts() *ScheduledPostUpdateOne {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to PublicationAttempt entities by IDs.
func (_u *ScheduledPostUpdateOne) RemoveAttemptIDs(ids ...string) *ScheduledPostUpdateOne {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to PublicationAttempt entities.
func (_u *ScheduledPostUpdateOne) RemoveAttempts(v ...*PublicationAttempt) *ScheduledPostUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// Where appends a list predicates to the ScheduledPostUpdate builder.
func (_u *ScheduledPostUpdateOne) Where(ps ...predicate.ScheduledPost) *ScheduledPostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduledPostUpdateOne) Select(field string, fields ...string) *ScheduledPostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScheduledPost entity.
func (_u *ScheduledPostUpdateOne) Save(ctx context.Context) (*ScheduledPost, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduledPostUpdateOne) SaveX(ctx context.Context) *ScheduledPost {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduledPostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduledPostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduledPostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scheduledpost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduledPostUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := scheduledpost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScheduledPost.status": %w`, err)}
		}
	}
	if _u.mutation.ChannelConnectionCleared() && len(_u.mutation.ChannelConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScheduledPost.channel_connection"`)
	}
	return nil
}

func (_u *ScheduledPostUpdateOne) sqlSave(ctx context.Context) (_node *ScheduledPost, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scheduledpost.Table, scheduledpost.Columns, sqlgraph.NewFieldSpec(scheduledpost.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScheduledPost.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scheduledpost.FieldID)
		for _, f := range fields {
			if !scheduledpost.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scheduledpost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScheduledFor(); ok {
		_spec.SetField(scheduledpost.FieldScheduledFor, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scheduledpost.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(scheduledpost.FieldCaption, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerRunID(); ok {
		_spec.SetField(scheduledpost.FieldTriggerRunID, field.TypeString, value)
	}
	if _u.mutation.TriggerRunIDCleared() {
		_spec.ClearField(scheduledpost.FieldTriggerRunID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scheduledpost.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduledpost.AttemptsTable,
			Columns: []string{scheduledpost.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduledpost.AttemptsTable,
			Columns: []string{scheduledpost.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduledpost.AttemptsTable,
			Columns: []string{scheduledpost.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScheduledPost{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scheduledpost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
