// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/channelconnection"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/publicationattempt"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/scheduledpost"
)

// ScheduledPostCreate is the builder for creating a ScheduledPost entity.
type ScheduledPostCreate struct {
	config
	mutation *ScheduledPostMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *ScheduledPostCreate) SetOrganizationID(v string) *ScheduledPostCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetVariantID sets the "variant_id" field.
func (_c *ScheduledPostCreate) SetVariantID(v string) *ScheduledPostCreate {
	_c.mutation.SetVariantID(v)
	return _c
}

// SetChannelConnectionID sets the "channel_connection_id" field.
func (_c *ScheduledPostCreate) SetChannelConnectionID(v string) *ScheduledPostCreate {
	_c.mutation.SetChannelConnectionID(v)
	return _c
}

// SetScheduledFor sets the "scheduled_for" field.
func (_c *ScheduledPostCreate) SetScheduledFor(v time.Time) *ScheduledPostCreate {
	_c.mutation.SetScheduledFor(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ScheduledPostCreate) SetStatus(v scheduledpost.Status) *ScheduledPostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ScheduledPostCreate) SetNillableStatus(v *scheduledpost.Status) *ScheduledPostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCaption sets the "caption" field.
func (_c *ScheduledPostCreate) SetCaption(v string) *ScheduledPostCreate {
	_c.mutation.SetCaption(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *ScheduledPostCreate) SetIdempotencyKey(v string) *ScheduledPostCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetTriggerRunID sets the "trigger_run_id" field.
func (_c *ScheduledPostCreate) SetTriggerRunID(v string) *ScheduledPostCreate {
	_c.mutation.SetTriggerRunID(v)
	return _c
}

// SetNillableTriggerRunID sets the "trigger_run_id" field if the given value is not nil.
func (_c *ScheduledPostCreate) SetNillableTriggerRunID(v *string) *ScheduledPostCreate {
	if v != nil {
		_c.SetTriggerRunID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScheduledPostCreate) SetCreatedAt(v time.Time) *ScheduledPostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScheduledPostCreate) SetNillableCreatedAt(v *time.Time) *ScheduledPostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScheduledPostCreate) SetUpdatedAt(v time.Time) *ScheduledPostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScheduledPostCreate) SetNillableUpdatedAt(v *time.Time) *ScheduledPostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScheduledPostCreate) SetID(v string) *ScheduledPostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetChannelConnection sets the "channel_connection" edge to the ChannelConnection entity.
func (_c *ScheduledPostCreate) SetChannelConnection(v *ChannelConnection) *ScheduledPostCreate {
	return _c.SetChannelConnectionID(v.ID)
}

// AddAttemptIDs adds the "attempts" edge to the PublicationAttempt entity by IDs.
func (_c *ScheduledPostCreate) AddAttemptIDs(ids ...string) *ScheduledPostCreate {
	_c.mutation.AddAttemptIDs(ids...)
	return _c
}

// AddAttempts adds the "attempts" edges to the PublicationAttempt entity.
func (_c *ScheduledPostCreate) AddAttempts(v ...*PublicationAttempt) *ScheduledPostCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttemptIDs(ids...)
}

// Mutation returns the ScheduledPostMutation object of the builder.
func (_c *ScheduledPostCreate) Mutation() *ScheduledPostMutation {
	return _c.mutation
}

// Save creates the ScheduledPost in the database.
func (_c *ScheduledPostCreate) Save(ctx context.Context) (*ScheduledPost, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduledPostCreate) SaveX(ctx context.Context) *ScheduledPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduledPostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduledPostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduledPostCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := scheduledpost.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := scheduledpost.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := scheduledpost.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduledPostCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "ScheduledPost.organization_id"`)}
	}
	if _, ok := _c.mutation.VariantID(); !ok {
		return &ValidationError{Name: "variant_id", err: errors.New(`ent: missing required field "ScheduledPost.variant_id"`)}
	}
	if _, ok := _c.mutation.ChannelConnectionID(); !ok {
		return &ValidationError{Name: "channel_connection_id", err: errors.New(`ent: missing required field "ScheduledPost.channel_connection_id"`)}
	}
	if _, ok := _c.mutation.ScheduledFor(); !ok {
		return &ValidationError{Name: "scheduled_for", err: errors.New(`ent: missing required field "ScheduledPost.scheduled_for"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ScheduledPost.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := scheduledpost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScheduledPost.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Caption(); !ok {
		return &ValidationError{Name: "caption", err: errors.New(`ent: missing required field "ScheduledPost.caption"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "ScheduledPost.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := scheduledpost.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ScheduledPost.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ScheduledPost.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ScheduledPost.updated_at"`)}
	}
	if len(_c.mutation.ChannelConnectionIDs()) == 0 {
		return &ValidationError{Name: "channel_connection", err: errors.New(`ent: missing required edge "ScheduledPost.channel_connection"`)}
	}
	return nil
}

func (_c *ScheduledPostCreate) sqlSave(ctx context.Context) (*ScheduledPost, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ScheduledPost.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduledPostCreate) createSpec() (*ScheduledPost, *sqlgraph.CreateSpec) {
	var (
		_node = &ScheduledPost{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scheduledpost.Table, sqlgraph.NewFieldSpec(scheduledpost.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(scheduledpost.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = value
	}
	if value, ok := _c.mutation.VariantID(); ok {
		_spec.SetField(scheduledpost.FieldVariantID, field.TypeString, value)
		_node.VariantID = value
	}
	if value, ok := _c.mutation.ScheduledFor(); ok {
		_spec.SetField(scheduledpost.FieldScheduledFor, field.TypeTime, value)
		_node.ScheduledFor = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(scheduledpost.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Caption(); ok {
		_spec.SetField(scheduledpost.FieldCaption, field.TypeString, value)
		_node.Caption = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(scheduledpost.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.TriggerRunID(); ok {
		_spec.SetField(scheduledpost.FieldTriggerRunID, field.TypeString, value)
		_node.TriggerRunID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(scheduledpost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(scheduledpost.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChannelConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scheduledpost.ChannelConnectionTable,
			Columns: []string{scheduledpost.ChannelConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelConnectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduledpost.AttemptsTable,
			Columns: []string{scheduledpost.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScheduledPostCreateBulk is the builder for creating many ScheduledPost entities in bulk.
type ScheduledPostCreateBulk struct {
	config
	err      error
	builders []*ScheduledPostCreate
}

// Save creates the ScheduledPost entities in the database.
func (_c *ScheduledPostCreateBulk) Save(ctx context.Context) ([]*ScheduledPost, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScheduledPost, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduledPostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduledPostCreateBulk) SaveX(ctx context.Context) []*ScheduledPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduledPostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduledPostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
