// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/workspacedeletion"
)

// WorkspaceDeletionUpdate is the builder for updating WorkspaceDeletion entities.
type WorkspaceDeletionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceDeletionMutation
}

// Where appends a list predicates to the WorkspaceDeletionUpdate builder.
func (_u *WorkspaceDeletionUpdate) Where(ps ...predicate.WorkspaceDeletion) *WorkspaceDeletionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkspaceDeletionUpdate) SetStatus(v workspacedeletion.Status) *WorkspaceDeletionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkspaceDeletionUpdate) SetNillableStatus(v *workspacedeletion.Status) *WorkspaceDeletionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the WorkspaceDeletionMutation object of the builder.
func (_u *WorkspaceDeletionUpdate) Mutation() *WorkspaceDeletionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceDeletionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceDeletionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceDeletionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceDeletionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceDeletionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := workspacedeletion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkspaceDeletion.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceDeletionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacedeletion.Table, workspacedeletion.Columns, sqlgraph.NewFieldSpec(workspacedeletion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workspacedeletion.FieldStatus, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacedeletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceDeletionUpdateOne is the builder for updating a single WorkspaceDeletion entity.
type WorkspaceDeletionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceDeletionMutation
}

// SetStatus sets the "status" field.
func (_u *WorkspaceDeletionUpdateOne) SetStatus(v workspacedeletion.Status) *WorkspaceDeletionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkspaceDeletionUpdateOne) SetNillableStatus(v *workspacedeletion.Status) *WorkspaceDeletionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the WorkspaceDeletionMutation object of the builder.
func (_u *WorkspaceDeletionUpdateOne) Mutation() *WorkspaceDeletionMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkspaceDeletionUpdate builder.
func (_u *WorkspaceDeletionUpdateOne) Where(ps ...predicate.WorkspaceDeletion) *WorkspaceDeletionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceDeletionUpdateOne) Select(field string, fields ...string) *WorkspaceDeletionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkspaceDeletion entity.
func (_u *WorkspaceDeletionUpdateOne) Save(ctx context.Context) (*WorkspaceDeletion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceDeletionUpdateOne) SaveX(ctx context.Context) *WorkspaceDeletion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceDeletionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceDeletionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceDeletionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := workspacedeletion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkspaceDeletion.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceDeletionUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceDeletion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacedeletion.Table, workspacedeletion.Columns, sqlgraph.NewFieldSpec(workspacedeletion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceDeletion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspacedeletion.FieldID)
		for _, f := range fields {
			if !workspacedeletion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspacedeletion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workspacedeletion.FieldStatus, field.TypeEnum, value)
	}
	_node = &WorkspaceDeletion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacedeletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
