// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/workspacedeletion"
)

// WorkspaceDeletion is the model entity for the WorkspaceDeletion schema.
type WorkspaceDeletion struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// Status holds the value of the "status" field.
	Status       workspacedeletion.Status `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkspaceDeletion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspacedeletion.FieldID, workspacedeletion.FieldOrganizationID, workspacedeletion.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkspaceDeletion fields.
func (_m *WorkspaceDeletion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspacedeletion.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case workspacedeletion.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = value.String
			}
		case workspacedeletion.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = workspacedeletion.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkspaceDeletion.
// This includes values selected through modifiers, order, etc.
func (_m *WorkspaceDeletion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WorkspaceDeletion.
// Note that you need to call WorkspaceDeletion.Unwrap() before calling this method if this WorkspaceDeletion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkspaceDeletion) Update() *WorkspaceDeletionUpdateOne {
	return NewWorkspaceDeletionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkspaceDeletion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkspaceDeletion) Unwrap() *WorkspaceDeletion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkspaceDeletion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkspaceDeletion) String() string {
	var builder strings.Builder
	builder.WriteString("WorkspaceDeletion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(_m.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// WorkspaceDeletions is a parsable slice of WorkspaceDeletion.
type WorkspaceDeletions []*WorkspaceDeletion
