// Code generated by ent, DO NOT EDIT.

package approval

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldID, id))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldOrganizationID, v))
}

// VariantID applies equality check predicate on the "variant_id" field. It's identical to VariantIDEQ.
func VariantID(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldVariantID, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldOrganizationID, v))
}

// OrganizationIDContains applies the Contains predicate on the "organization_id" field.
func OrganizationIDContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldOrganizationID, v))
}

// OrganizationIDHasPrefix applies the HasPrefix predicate on the "organization_id" field.
func OrganizationIDHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldOrganizationID, v))
}

// OrganizationIDHasSuffix applies the HasSuffix predicate on the "organization_id" field.
func OrganizationIDHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldOrganizationID, v))
}

// OrganizationIDEqualFold applies the EqualFold predicate on the "organization_id" field.
func OrganizationIDEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldOrganizationID, v))
}

// OrganizationIDContainsFold applies the ContainsFold predicate on the "organization_id" field.
func OrganizationIDContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldOrganizationID, v))
}

// VariantIDEQ applies the EQ predicate on the "variant_id" field.
func VariantIDEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldVariantID, v))
}

// VariantIDNEQ applies the NEQ predicate on the "variant_id" field.
func VariantIDNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldVariantID, v))
}

// VariantIDIn applies the In predicate on the "variant_id" field.
func VariantIDIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldVariantID, vs...))
}

// VariantIDNotIn applies the NotIn predicate on the "variant_id" field.
func VariantIDNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldVariantID, vs...))
}

// VariantIDGT applies the GT predicate on the "variant_id" field.
func VariantIDGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldVariantID, v))
}

// VariantIDGTE applies the GTE predicate on the "variant_id" field.
func VariantIDGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldVariantID, v))
}

// VariantIDLT applies the LT predicate on the "variant_id" field.
func VariantIDLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldVariantID, v))
}

// VariantIDLTE applies the LTE predicate on the "variant_id" field.
func VariantIDLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldVariantID, v))
}

// VariantIDContains applies the Contains predicate on the "variant_id" field.
func VariantIDContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldVariantID, v))
}

// VariantIDHasPrefix applies the HasPrefix predicate on the "variant_id" field.
func VariantIDHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldVariantID, v))
}

// VariantIDHasSuffix applies the HasSuffix predicate on the "variant_id" field.
func VariantIDHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldVariantID, v))
}

// VariantIDEqualFold applies the EqualFold predicate on the "variant_id" field.
func VariantIDEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldVariantID, v))
}

// VariantIDContainsFold applies the ContainsFold predicate on the "variant_id" field.
func VariantIDContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldVariantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldStatus, vs...))
}

// HasVariant applies the HasEdge predicate on the "variant" edge.
func HasVariant() predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, VariantTable, VariantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVariantWith applies the HasEdge predicate on the "variant" edge with a given conditions (other predicates).
func HasVariantWith(preds ...predicate.CreativeVariant) predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := newVariantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.NotPredicates(p))
}
