// Code generated by ent, DO NOT EDIT.

package auditlog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditlog type in the database.
	Label = "audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organizationId"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "requestId"
	// FieldActorType holds the string denoting the actor_type field in the database.
	FieldActorType = "actorType"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actorUserId"
	// FieldActorDisplay holds the string denoting the actor_display field in the database.
	FieldActorDisplay = "actorDisplay"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entityType"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entityId"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldSearchText holds the string denoting the search_text field in the database.
	FieldSearchText = "searchText"
	// Table holds the table name of the auditlog in the database.
	Table = "audit_log"
)

// Columns holds all SQL columns for auditlog fields.
var Columns = []string{
	FieldID,
	FieldOrganizationID,
	FieldCreatedAt,
	FieldRequestID,
	FieldActorType,
	FieldActorUserID,
	FieldActorDisplay,
	FieldAction,
	FieldOutcome,
	FieldEntityType,
	FieldEntityID,
	FieldMetadata,
	FieldSearchText,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultSearchText holds the default value on creation for the "search_text" field.
	DefaultSearchText string
)

// ActorType defines the type for the "actor_type" enum field.
type ActorType string

// ActorType values.
const (
	ActorTypeUSER    ActorType = "USER"
	ActorTypeSERVICE ActorType = "SERVICE"
	ActorTypeSUPPORT ActorType = "SUPPORT"
	ActorTypeWEBHOOK ActorType = "WEBHOOK"
)

func (at ActorType) String() string {
	return string(at)
}

// ActorTypeValidator is a validator for the "actor_type" field enum values. It is called by the builders before save.
func ActorTypeValidator(at ActorType) error {
	switch at {
	case ActorTypeUSER, ActorTypeSERVICE, ActorTypeSUPPORT, ActorTypeWEBHOOK:
		return nil
	default:
		return fmt.Errorf("auditlog: invalid enum value for actor_type field: %q", at)
	}
}

// Outcome defines the type for the "outcome" enum field.
type Outcome string

// OutcomeSUCCEEDED is the default value of the Outcome enum.
const DefaultOutcome = OutcomeSUCCEEDED

// Outcome values.
const (
	OutcomeSUCCEEDED Outcome = "SUCCEEDED"
	OutcomeFAILED    Outcome = "FAILED"
	OutcomeDENIED    Outcome = "DENIED"
)

func (o Outcome) String() string {
	return string(o)
}

// OutcomeValidator is a validator for the "outcome" field enum values. It is called by the builders before save.
func OutcomeValidator(o Outcome) error {
	switch o {
	case OutcomeSUCCEEDED, OutcomeFAILED, OutcomeDENIED:
		return nil
	default:
		return fmt.Errorf("auditlog: invalid enum value for outcome field: %q", o)
	}
}

// OrderOption defines the ordering options for the AuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByActorType orders the results by the actor_type field.
func ByActorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorType, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByActorDisplay orders the results by the actor_display field.
func ByActorDisplay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorDisplay, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByOutcome orders the results by the outcome field.
func ByOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcome, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// BySearchText orders the results by the search_text field.
func BySearchText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSearchText, opts...).ToFunc()
}
