// Code generated by ent, DO NOT EDIT.

package auditoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditoutbox type in the database.
	Label = "audit_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuditLogID holds the string denoting the audit_log_id field in the database.
	FieldAuditLogID = "auditLogId"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// Table holds the table name of the auditoutbox in the database.
	Table = "audit_outbox"
)

// Columns holds all SQL columns for auditoutbox fields.
var Columns = []string{
	FieldID,
	FieldAuditLogID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AuditOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAuditLogID orders the results by the audit_log_id field.
func ByAuditLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditLogID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
