// Code generated by ent, DO NOT EDIT.

package auditoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldContainsFold(FieldID, id))
}

// AuditLogID applies equality check predicate on the "audit_log_id" field. It's identical to AuditLogIDEQ.
func AuditLogID(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEQ(FieldAuditLogID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// AuditLogIDEQ applies the EQ predicate on the "audit_log_id" field.
func AuditLogIDEQ(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEQ(FieldAuditLogID, v))
}

// AuditLogIDNEQ applies the NEQ predicate on the "audit_log_id" field.
func AuditLogIDNEQ(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldNEQ(FieldAuditLogID, v))
}

// AuditLogIDIn applies the In predicate on the "audit_log_id" field.
func AuditLogIDIn(vs ...string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldIn(FieldAuditLogID, vs...))
}

// AuditLogIDNotIn applies the NotIn predicate on the "audit_log_id" field.
func AuditLogIDNotIn(vs ...string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldNotIn(FieldAuditLogID, vs...))
}

// AuditLogIDGT applies the GT predicate on the "audit_log_id" field.
func AuditLogIDGT(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldGT(FieldAuditLogID, v))
}

// AuditLogIDGTE applies the GTE predicate on the "audit_log_id" field.
func AuditLogIDGTE(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldGTE(FieldAuditLogID, v))
}

// AuditLogIDLT applies the LT predicate on the "audit_log_id" field.
func AuditLogIDLT(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldLT(FieldAuditLogID, v))
}

// AuditLogIDLTE applies the LTE predicate on the "audit_log_id" field.
func AuditLogIDLTE(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldLTE(FieldAuditLogID, v))
}

// AuditLogIDContains applies the Contains predicate on the "audit_log_id" field.
func AuditLogIDContains(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldContains(FieldAuditLogID, v))
}

// AuditLogIDHasPrefix applies the HasPrefix predicate on the "audit_log_id" field.
func AuditLogIDHasPrefix(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldHasPrefix(FieldAuditLogID, v))
}

// AuditLogIDHasSuffix applies the HasSuffix predicate on the "audit_log_id" field.
func AuditLogIDHasSuffix(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldHasSuffix(FieldAuditLogID, v))
}

// AuditLogIDEqualFold applies the EqualFold predicate on the "audit_log_id" field.
func AuditLogIDEqualFold(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEqualFold(FieldAuditLogID, v))
}

// AuditLogIDContainsFold applies the ContainsFold predicate on the "audit_log_id" field.
func AuditLogIDContainsFold(v string) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldContainsFold(FieldAuditLogID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditOutbox) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditOutbox) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditOutbox) predicate.AuditOutbox {
	return predicate.AuditOutbox(sql.NotPredicates(p))
}
