// Code generated by ent, DO NOT EDIT.

package channelconnection

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channelconnection type in the database.
	Label = "channel_connection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organizationId"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldExternalAccountID holds the string denoting the external_account_id field in the database.
	FieldExternalAccountID = "externalAccountId"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldProviderSettings holds the string denoting the provider_settings field in the database.
	FieldProviderSettings = "providerSettings"
	// FieldSecretReference holds the string denoting the secret_reference field in the database.
	FieldSecretReference = "secretReference"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedByUserID holds the string denoting the created_by_user_id field in the database.
	FieldCreatedByUserID = "createdByUserId"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updatedAt"
	// EdgeScheduledPosts holds the string denoting the scheduled_posts edge name in mutations.
	EdgeScheduledPosts = "scheduled_posts"
	// Table holds the table name of the channelconnection in the database.
	Table = "channel_connection"
	// ScheduledPostsTable is the table that holds the scheduled_posts relation/edge.
	ScheduledPostsTable = "scheduled_post"
	// ScheduledPostsInverseTable is the table name for the ScheduledPost entity.
	// It exists in this package in order to avoid circular dependency with the "scheduledpost" package.
	ScheduledPostsInverseTable = "scheduled_post"
	// ScheduledPostsColumn is the table column denoting the scheduled_posts relation/edge.
	ScheduledPostsColumn = "channelConnectionId"
)

// Columns holds all SQL columns for channelconnection fields.
var Columns = []string{
	FieldID,
	FieldOrganizationID,
	FieldProvider,
	FieldExternalAccountID,
	FieldPlatform,
	FieldProviderSettings,
	FieldSecretReference,
	FieldStatus,
	FieldCreatedByUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ExternalAccountIDValidator is a validator for the "external_account_id" field. It is called by the builders before save.
	ExternalAccountIDValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// DefaultProviderSettings holds the default value on creation for the "provider_settings" field.
	DefaultProviderSettings map[string]interface{}
	// SecretReferenceValidator is a validator for the "secret_reference" field. It is called by the builders before save.
	SecretReferenceValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusACTIVE is the default value of the Status enum.
const DefaultStatus = StatusACTIVE

// Status values.
const (
	StatusACTIVE   Status = "ACTIVE"
	StatusDISABLED Status = "DISABLED"
	StatusREVOKED  Status = "REVOKED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusACTIVE, StatusDISABLED, StatusREVOKED:
		return nil
	default:
		return fmt.Errorf("channelconnection: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ChannelConnection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByExternalAccountID orders the results by the external_account_id field.
func ByExternalAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalAccountID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// BySecretReference orders the results by the secret_reference field.
func BySecretReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretReference, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedByUserID orders the results by the created_by_user_id field.
func ByCreatedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScheduledPostsCount orders the results by scheduled_posts count.
func ByScheduledPostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newScheduledPostsStep(), opts...)
	}
}

// ByScheduledPosts orders the results by scheduled_posts terms.
func ByScheduledPosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScheduledPostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newScheduledPostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScheduledPostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ScheduledPostsTable, ScheduledPostsColumn),
	)
}
