// Code generated by ent, DO NOT EDIT.

package channelconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContainsFold(FieldID, id))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldOrganizationID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldProvider, v))
}

// ExternalAccountID applies equality check predicate on the "external_account_id" field. It's identical to ExternalAccountIDEQ.
func ExternalAccountID(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldExternalAccountID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldPlatform, v))
}

// SecretReference applies equality check predicate on the "secret_reference" field. It's identical to SecretReferenceEQ.
func SecretReference(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldSecretReference, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldOrganizationID, v))
}

// OrganizationIDContains applies the Contains predicate on the "organization_id" field.
func OrganizationIDContains(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContains(FieldOrganizationID, v))
}

// OrganizationIDHasPrefix applies the HasPrefix predicate on the "organization_id" field.
func OrganizationIDHasPrefix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasPrefix(FieldOrganizationID, v))
}

// OrganizationIDHasSuffix applies the HasSuffix predicate on the "organization_id" field.
func OrganizationIDHasSuffix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasSuffix(FieldOrganizationID, v))
}

// OrganizationIDEqualFold applies the EqualFold predicate on the "organization_id" field.
func OrganizationIDEqualFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEqualFold(FieldOrganizationID, v))
}

// OrganizationIDContainsFold applies the ContainsFold predicate on the "organization_id" field.
func OrganizationIDContainsFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContainsFold(FieldOrganizationID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContainsFold(FieldProvider, v))
}

// ExternalAccountIDEQ applies the EQ predicate on the "external_account_id" field.
func ExternalAccountIDEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldExternalAccountID, v))
}

// ExternalAccountIDNEQ applies the NEQ predicate on the "external_account_id" field.
func ExternalAccountIDNEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldExternalAccountID, v))
}

// ExternalAccountIDIn applies the In predicate on the "external_account_id" field.
func ExternalAccountIDIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldExternalAccountID, vs...))
}

// ExternalAccountIDNotIn applies the NotIn predicate on the "external_account_id" field.
func ExternalAccountIDNotIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldExternalAccountID, vs...))
}

// ExternalAccountIDGT applies the GT predicate on the "external_account_id" field.
func ExternalAccountIDGT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldExternalAccountID, v))
}

// ExternalAccountIDGTE applies the GTE predicate on the "external_account_id" field.
func ExternalAccountIDGTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldExternalAccountID, v))
}

// ExternalAccountIDLT applies the LT predicate on the "external_account_id" field.
func ExternalAccountIDLT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldExternalAccountID, v))
}

// ExternalAccountIDLTE applies the LTE predicate on the "external_account_id" field.
func ExternalAccountIDLTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldExternalAccountID, v))
}

// ExternalAccountIDContains applies the Contains predicate on the "external_account_id" field.
func ExternalAccountIDContains(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContains(FieldExternalAccountID, v))
}

// ExternalAccountIDHasPrefix applies the HasPrefix predicate on the "external_account_id" field.
func ExternalAccountIDHasPrefix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasPrefix(FieldExternalAccountID, v))
}

// ExternalAccountIDHasSuffix applies the HasSuffix predicate on the "external_account_id" field.
func ExternalAccountIDHasSuffix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasSuffix(FieldExternalAccountID, v))
}

// ExternalAccountIDEqualFold applies the EqualFold predicate on the "external_account_id" field.
func ExternalAccountIDEqualFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEqualFold(FieldExternalAccountID, v))
}

// ExternalAccountIDContainsFold applies the ContainsFold predicate on the "external_account_id" field.
func ExternalAccountIDContainsFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContainsFold(FieldExternalAccountID, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContainsFold(FieldPlatform, v))
}

// SecretReferenceEQ applies the EQ predicate on the "secret_reference" field.
func SecretReferenceEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldSecretReference, v))
}

// SecretReferenceNEQ applies the NEQ predicate on the "secret_reference" field.
func SecretReferenceNEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldSecretReference, v))
}

// SecretReferenceIn applies the In predicate on the "secret_reference" field.
func SecretReferenceIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldSecretReference, vs...))
}

// SecretReferenceNotIn applies the NotIn predicate on the "secret_reference" field.
func SecretReferenceNotIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldSecretReference, vs...))
}

// SecretReferenceGT applies the GT predicate on the "secret_reference" field.
func SecretReferenceGT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldSecretReference, v))
}

// SecretReferenceGTE applies the GTE predicate on the "secret_reference" field.
func SecretReferenceGTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldSecretReference, v))
}

// SecretReferenceLT applies the LT predicate on the "secret_reference" field.
func SecretReferenceLT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldSecretReference, v))
}

// SecretReferenceLTE applies the LTE predicate on the "secret_reference" field.
func SecretReferenceLTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldSecretReference, v))
}

// SecretReferenceContains applies the Contains predicate on the "secret_reference" field.
func SecretReferenceContains(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContains(FieldSecretReference, v))
}

// SecretReferenceHasPrefix applies the HasPrefix predicate on the "secret_reference" field.
func SecretReferenceHasPrefix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasPrefix(FieldSecretReference, v))
}

// SecretReferenceHasSuffix applies the HasSuffix predicate on the "secret_reference" field.
func SecretReferenceHasSuffix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasSuffix(FieldSecretReference, v))
}

// SecretReferenceEqualFold applies the EqualFold predicate on the "secret_reference" field.
func SecretReferenceEqualFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEqualFold(FieldSecretReference, v))
}

// SecretReferenceContainsFold applies the ContainsFold predicate on the "secret_reference" field.
func SecretReferenceContainsFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContainsFold(FieldSecretReference, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDGT applies the GT predicate on the "created_by_user_id" field.
func CreatedByUserIDGT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldCreatedByUserID, v))
}

// CreatedByUserIDGTE applies the GTE predicate on the "created_by_user_id" field.
func CreatedByUserIDGTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDLT applies the LT predicate on the "created_by_user_id" field.
func CreatedByUserIDLT(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldCreatedByUserID, v))
}

// CreatedByUserIDLTE applies the LTE predicate on the "created_by_user_id" field.
func CreatedByUserIDLTE(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDContains applies the Contains predicate on the "created_by_user_id" field.
func CreatedByUserIDContains(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContains(FieldCreatedByUserID, v))
}

// CreatedByUserIDHasPrefix applies the HasPrefix predicate on the "created_by_user_id" field.
func CreatedByUserIDHasPrefix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasPrefix(FieldCreatedByUserID, v))
}

// CreatedByUserIDHasSuffix applies the HasSuffix predicate on the "created_by_user_id" field.
func CreatedByUserIDHasSuffix(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldHasSuffix(FieldCreatedByUserID, v))
}

// CreatedByUserIDEqualFold applies the EqualFold predicate on the "created_by_user_id" field.
func CreatedByUserIDEqualFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEqualFold(FieldCreatedByUserID, v))
}

// CreatedByUserIDContainsFold applies the ContainsFold predicate on the "created_by_user_id" field.
func CreatedByUserIDContainsFold(v string) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldContainsFold(FieldCreatedByUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasScheduledPosts applies the HasEdge predicate on the "scheduled_posts" edge.
func HasScheduledPosts() predicate.ChannelConnection {
	return predicate.ChannelConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ScheduledPostsTable, ScheduledPostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScheduledPostsWith applies the HasEdge predicate on the "scheduled_posts" edge with a given conditions (other predicates).
func HasScheduledPostsWith(preds ...predicate.ScheduledPost) predicate.ChannelConnection {
	return predicate.ChannelConnection(func(s *sql.Selector) {
		step := newScheduledPostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelConnection) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelConnection) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelConnection) predicate.ChannelConnection {
	return predicate.ChannelConnection(sql.NotPredicates(p))
}
