// Code generated by ent, DO NOT EDIT.

package asset

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the asset type in the database.
	Label = "asset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organizationId"
	// FieldObjectKey holds the string denoting the object_key field in the database.
	FieldObjectKey = "objectKey"
	// FieldMediaType holds the string denoting the media_type field in the database.
	FieldMediaType = "mediaType"
	// EdgeVariants holds the string denoting the variants edge name in mutations.
	EdgeVariants = "variants"
	// Table holds the table name of the asset in the database.
	Table = "asset"
	// VariantsTable is the table that holds the variants relation/edge.
	VariantsTable = "creative_variant"
	// VariantsInverseTable is the table name for the CreativeVariant entity.
	// It exists in this package in order to avoid circular dependency with the "creativevariant" package.
	VariantsInverseTable = "creative_variant"
	// VariantsColumn is the table column denoting the variants relation/edge.
	VariantsColumn = "sourceAssetId"
)

// Columns holds all SQL columns for asset fields.
var Columns = []string{
	FieldID,
	FieldOrganizationID,
	FieldObjectKey,
	FieldMediaType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Asset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByObjectKey orders the results by the object_key field.
func ByObjectKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectKey, opts...).ToFunc()
}

// ByMediaType orders the results by the media_type field.
func ByMediaType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaType, opts...).ToFunc()
}

// ByVariantsCount orders the results by variants count.
func ByVariantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVariantsStep(), opts...)
	}
}

// ByVariants orders the results by variants terms.
func ByVariants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVariantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVariantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VariantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, VariantsTable, VariantsColumn),
	)
}
