// Code generated by ent, DO NOT EDIT.

package auditdraindelivery

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditdraindelivery type in the database.
	Label = "audit_drain_delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDrainID holds the string denoting the drain_id field in the database.
	FieldDrainID = "drainId"
	// FieldOutboxID holds the string denoting the outbox_id field in the database.
	FieldOutboxID = "outboxId"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attemptCount"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "nextAttemptAt"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updatedAt"
	// Table holds the table name of the auditdraindelivery in the database.
	Table = "audit_drain_delivery"
)

// Columns holds all SQL columns for auditdraindelivery fields.
var Columns = []string{
	FieldID,
	FieldDrainID,
	FieldOutboxID,
	FieldStatus,
	FieldAttemptCount,
	FieldNextAttemptAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultNextAttemptAt holds the default value on creation for the "next_attempt_at" field.
	DefaultNextAttemptAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING    Status = "PENDING"
	StatusPROCESSING Status = "PROCESSING"
	StatusDELIVERED  Status = "DELIVERED"
	StatusFAILED     Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusPROCESSING, StatusDELIVERED, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("auditdraindelivery: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AuditDrainDelivery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDrainID orders the results by the drain_id field.
func ByDrainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrainID, opts...).ToFunc()
}

// ByOutboxID orders the results by the outbox_id field.
func ByOutboxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboxID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
