// Code generated by ent, DO NOT EDIT.

package publicationattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PlaybookMediaLLC/screenshot-studio/services/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContainsFold(FieldID, id))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldOrganizationID, v))
}

// ScheduledPostID applies equality check predicate on the "scheduled_post_id" field. It's identical to ScheduledPostIDEQ.
func ScheduledPostID(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldScheduledPostID, v))
}

// AttemptNumber applies equality check predicate on the "attempt_number" field. It's identical to AttemptNumberEQ.
func AttemptNumber(v int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldAttemptNumber, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldCompletedAt, v))
}

// ProviderPostID applies equality check predicate on the "provider_post_id" field. It's identical to ProviderPostIDEQ.
func ProviderPostID(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldProviderPostID, v))
}

// FailureCode applies equality check predicate on the "failure_code" field. It's identical to FailureCodeEQ.
func FailureCode(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldFailureCode, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldOrganizationID, v))
}

// OrganizationIDContains applies the Contains predicate on the "organization_id" field.
func OrganizationIDContains(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContains(FieldOrganizationID, v))
}

// OrganizationIDHasPrefix applies the HasPrefix predicate on the "organization_id" field.
func OrganizationIDHasPrefix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasPrefix(FieldOrganizationID, v))
}

// OrganizationIDHasSuffix applies the HasSuffix predicate on the "organization_id" field.
func OrganizationIDHasSuffix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasSuffix(FieldOrganizationID, v))
}

// OrganizationIDEqualFold applies the EqualFold predicate on the "organization_id" field.
func OrganizationIDEqualFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEqualFold(FieldOrganizationID, v))
}

// OrganizationIDContainsFold applies the ContainsFold predicate on the "organization_id" field.
func OrganizationIDContainsFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContainsFold(FieldOrganizationID, v))
}

// ScheduledPostIDEQ applies the EQ predicate on the "scheduled_post_id" field.
func ScheduledPostIDEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldScheduledPostID, v))
}

// ScheduledPostIDNEQ applies the NEQ predicate on the "scheduled_post_id" field.
func ScheduledPostIDNEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldScheduledPostID, v))
}

// ScheduledPostIDIn applies the In predicate on the "scheduled_post_id" field.
func ScheduledPostIDIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldScheduledPostID, vs...))
}

// ScheduledPostIDNotIn applies the NotIn predicate on the "scheduled_post_id" field.
func ScheduledPostIDNotIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldScheduledPostID, vs...))
}

// ScheduledPostIDGT applies the GT predicate on the "scheduled_post_id" field.
func ScheduledPostIDGT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldScheduledPostID, v))
}

// ScheduledPostIDGTE applies the GTE predicate on the "scheduled_post_id" field.
func ScheduledPostIDGTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldScheduledPostID, v))
}

// ScheduledPostIDLT applies the LT predicate on the "scheduled_post_id" field.
func ScheduledPostIDLT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldScheduledPostID, v))
}

// ScheduledPostIDLTE applies the LTE predicate on the "scheduled_post_id" field.
func ScheduledPostIDLTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldScheduledPostID, v))
}

// ScheduledPostIDContains applies the Contains predicate on the "scheduled_post_id" field.
func ScheduledPostIDContains(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContains(FieldScheduledPostID, v))
}

// ScheduledPostIDHasPrefix applies the HasPrefix predicate on the "scheduled_post_id" field.
func ScheduledPostIDHasPrefix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasPrefix(FieldScheduledPostID, v))
}

// ScheduledPostIDHasSuffix applies the HasSuffix predicate on the "scheduled_post_id" field.
func ScheduledPostIDHasSuffix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasSuffix(FieldScheduledPostID, v))
}

// ScheduledPostIDEqualFold applies the EqualFold predicate on the "scheduled_post_id" field.
func ScheduledPostIDEqualFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEqualFold(FieldScheduledPostID, v))
}

// ScheduledPostIDContainsFold applies the ContainsFold predicate on the "scheduled_post_id" field.
func ScheduledPostIDContainsFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContainsFold(FieldScheduledPostID, v))
}

// AttemptNumberEQ applies the EQ predicate on the "attempt_number" field.
func AttemptNumberEQ(v int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldAttemptNumber, v))
}

// AttemptNumberNEQ applies the NEQ predicate on the "attempt_number" field.
func AttemptNumberNEQ(v int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldAttemptNumber, v))
}

// AttemptNumberIn applies the In predicate on the "attempt_number" field.
func AttemptNumberIn(vs ...int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldAttemptNumber, vs...))
}

// AttemptNumberNotIn applies the NotIn predicate on the "attempt_number" field.
func AttemptNumberNotIn(vs ...int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldAttemptNumber, vs...))
}

// AttemptNumberGT applies the GT predicate on the "attempt_number" field.
func AttemptNumberGT(v int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldAttemptNumber, v))
}

// AttemptNumberGTE applies the GTE predicate on the "attempt_number" field.
func AttemptNumberGTE(v int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldAttemptNumber, v))
}

// AttemptNumberLT applies the LT predicate on the "attempt_number" field.
func AttemptNumberLT(v int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldAttemptNumber, v))
}

// AttemptNumberLTE applies the LTE predicate on the "attempt_number" field.
func AttemptNumberLTE(v int) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldAttemptNumber, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotNull(FieldCompletedAt))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v Outcome) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v Outcome) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...Outcome) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...Outcome) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeIsNil applies the IsNil predicate on the "outcome" field.
func OutcomeIsNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIsNull(FieldOutcome))
}

// OutcomeNotNil applies the NotNil predicate on the "outcome" field.
func OutcomeNotNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotNull(FieldOutcome))
}

// ProviderPostIDEQ applies the EQ predicate on the "provider_post_id" field.
func ProviderPostIDEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldProviderPostID, v))
}

// ProviderPostIDNEQ applies the NEQ predicate on the "provider_post_id" field.
func ProviderPostIDNEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldProviderPostID, v))
}

// ProviderPostIDIn applies the In predicate on the "provider_post_id" field.
func ProviderPostIDIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldProviderPostID, vs...))
}

// ProviderPostIDNotIn applies the NotIn predicate on the "provider_post_id" field.
func ProviderPostIDNotIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldProviderPostID, vs...))
}

// ProviderPostIDGT applies the GT predicate on the "provider_post_id" field.
func ProviderPostIDGT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldProviderPostID, v))
}

// ProviderPostIDGTE applies the GTE predicate on the "provider_post_id" field.
func ProviderPostIDGTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldProviderPostID, v))
}

// ProviderPostIDLT applies the LT predicate on the "provider_post_id" field.
func ProviderPostIDLT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldProviderPostID, v))
}

// ProviderPostIDLTE applies the LTE predicate on the "provider_post_id" field.
func ProviderPostIDLTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldProviderPostID, v))
}

// ProviderPostIDContains applies the Contains predicate on the "provider_post_id" field.
func ProviderPostIDContains(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContains(FieldProviderPostID, v))
}

// ProviderPostIDHasPrefix applies the HasPrefix predicate on the "provider_post_id" field.
func ProviderPostIDHasPrefix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasPrefix(FieldProviderPostID, v))
}

// ProviderPostIDHasSuffix applies the HasSuffix predicate on the "provider_post_id" field.
func ProviderPostIDHasSuffix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasSuffix(FieldProviderPostID, v))
}

// ProviderPostIDIsNil applies the IsNil predicate on the "provider_post_id" field.
func ProviderPostIDIsNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIsNull(FieldProviderPostID))
}

// ProviderPostIDNotNil applies the NotNil predicate on the "provider_post_id" field.
func ProviderPostIDNotNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotNull(FieldProviderPostID))
}

// ProviderPostIDEqualFold applies the EqualFold predicate on the "provider_post_id" field.
func ProviderPostIDEqualFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEqualFold(FieldProviderPostID, v))
}

// ProviderPostIDContainsFold applies the ContainsFold predicate on the "provider_post_id" field.
func ProviderPostIDContainsFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContainsFold(FieldProviderPostID, v))
}

// FailureCodeEQ applies the EQ predicate on the "failure_code" field.
func FailureCodeEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEQ(FieldFailureCode, v))
}

// FailureCodeNEQ applies the NEQ predicate on the "failure_code" field.
func FailureCodeNEQ(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNEQ(FieldFailureCode, v))
}

// FailureCodeIn applies the In predicate on the "failure_code" field.
func FailureCodeIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIn(FieldFailureCode, vs...))
}

// FailureCodeNotIn applies the NotIn predicate on the "failure_code" field.
func FailureCodeNotIn(vs ...string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotIn(FieldFailureCode, vs...))
}

// FailureCodeGT applies the GT predicate on the "failure_code" field.
func FailureCodeGT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGT(FieldFailureCode, v))
}

// FailureCodeGTE applies the GTE predicate on the "failure_code" field.
func FailureCodeGTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldGTE(FieldFailureCode, v))
}

// FailureCodeLT applies the LT predicate on the "failure_code" field.
func FailureCodeLT(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLT(FieldFailureCode, v))
}

// FailureCodeLTE applies the LTE predicate on the "failure_code" field.
func FailureCodeLTE(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldLTE(FieldFailureCode, v))
}

// FailureCodeContains applies the Contains predicate on the "failure_code" field.
func FailureCodeContains(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContains(FieldFailureCode, v))
}

// FailureCodeHasPrefix applies the HasPrefix predicate on the "failure_code" field.
func FailureCodeHasPrefix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasPrefix(FieldFailureCode, v))
}

// FailureCodeHasSuffix applies the HasSuffix predicate on the "failure_code" field.
func FailureCodeHasSuffix(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldHasSuffix(FieldFailureCode, v))
}

// FailureCodeIsNil applies the IsNil predicate on the "failure_code" field.
func FailureCodeIsNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldIsNull(FieldFailureCode))
}

// FailureCodeNotNil applies the NotNil predicate on the "failure_code" field.
func FailureCodeNotNil() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldNotNull(FieldFailureCode))
}

// FailureCodeEqualFold applies the EqualFold predicate on the "failure_code" field.
func FailureCodeEqualFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldEqualFold(FieldFailureCode, v))
}

// FailureCodeContainsFold applies the ContainsFold predicate on the "failure_code" field.
func FailureCodeContainsFold(v string) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.FieldContainsFold(FieldFailureCode, v))
}

// HasScheduledPost applies the HasEdge predicate on the "scheduled_post" edge.
func HasScheduledPost() predicate.PublicationAttempt {
	return predicate.PublicationAttempt(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScheduledPostTable, ScheduledPostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScheduledPostWith applies the HasEdge predicate on the "scheduled_post" edge with a given conditions (other predicates).
func HasScheduledPostWith(preds ...predicate.ScheduledPost) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(func(s *sql.Selector) {
		step := newScheduledPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PublicationAttempt) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PublicationAttempt) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PublicationAttempt) predicate.PublicationAttempt {
	return predicate.PublicationAttempt(sql.NotPredicates(p))
}
